/* Una frase de ejemplo (y nota cuando hace falta) para cada palabra del vocabulario.
   Formato: palabra: [frase en inglés, nota opcional en español] */

export const EXAMPLES = {
  /* --- académicas frecuentes --- */
  consultation: ["The policy was drafted in consultation with local residents.", "in consultation with = de acuerdo con, tras consultar a."],
  conclusively: ["Nothing in the data proves conclusively that the drug works."],
  disruptive: ["Streaming proved far more disruptive to the industry than anyone predicted."],
  intolerable: ["The working conditions in the warehouse were frankly intolerable."],
  immune: ["Nobody is immune to flattery, however rational they claim to be.", "immune TO. Preposición dependiente."],
  reckless: ["He was charged with reckless driving after the accident."],
  offspring: ["The birds feed their offspring for several weeks after hatching.", "Invariable en plural: no existe «offsprings»."],
  strive: ["Small publishers strive to compete with the major chains.", "strive FOR sth / strive TO do sth."],
  thereafter: ["She left in 1998 and rarely returned thereafter.", "Registro formal, típico de textos legales y académicos."],
  scramble: ["Ministers scrambled to contain the damage after the leak.", "También «revolver»: scrambled eggs."],
  underway: ["Renovation work is already underway on the east wing.", "Se escribe junto cuando va con «be»."],
  strategically: ["The cameras were placed strategically around the perimeter."],
  scattered: ["Papers were scattered across every surface in the office."],
  remorse: ["He showed not a flicker of remorse during the trial.", "Incontable: «no remorse», nunca «a remorse»."],
  complimentary: ["Guests receive a complimentary breakfast.", "Dos sentidos: gratuito y elogioso. No confundir con «complementary» (complementario)."],
  additive: ["The label lists three artificial additives."],
  burial: ["The burial took place quietly, without press."],
  blunt: ["To be blunt, the manuscript is not ready.", "También «romo»: a blunt knife."],
  totalitarian: ["The novel imagines life under a totalitarian regime."],

  /* --- registro alto --- */
  heinous: ["The court described the attack as a heinous crime.", "Se pronuncia /ˈheɪnəs/, no «hei-nious»."],
  pensive: ["She fell pensive when the subject came up."],
  pristine: ["The manuscript survived in pristine condition."],
  zealous: ["He was a zealous defender of the old rules.", "Ojo con el matiz: puede sonar a exceso de celo."],
  quaint: ["They stayed in a quaint cottage on the coast.", "Cuidado: aplicado a ideas puede ser condescendiente."],
  eloquent: ["Her closing statement was unusually eloquent."],
  swarthy: ["The portrait shows a swarthy, weather-beaten sailor.", "Literario y algo anticuado; úsalo solo en comprensión."],
  lozenge: ["He sucked a throat lozenge through the whole meeting."],
  alabaster: ["The tomb is carved from a single block of alabaster."],
  obfuscate: ["The report seems designed to obfuscate rather than explain.", "Implica ocultar a propósito, no simplemente confundir."],
  prevaricate: ["Stop prevaricating and give me a straight answer.", "FALSO AMIGO: es «andarse con evasivas», no «prevaricar» (que sería «to pervert the course of justice»)."],
  burble: ["A stream burbled somewhere below the path."],
  fustigate: ["Editorials fustigated the government for its inaction.", "Muy formal y raro; casi solo aparece en textos de examen."],

  /* --- ampliación de registro --- */
  ubiquitous: ["Smartphones are now ubiquitous in classrooms."],
  tenuous: ["The link between the two events is tenuous at best."],
  meticulous: ["He kept meticulous records of every transaction."],
  opaque: ["The funding rules remain opaque to most applicants.", "Se usa mucho en sentido figurado: difícil de entender."],
  candid: ["In a candid interview, she admitted the project had failed.", "No confundir con «cándido» (naive)."],
  plausible: ["That is a plausible explanation, but it isn't proven."],
  cogent: ["She made a cogent case for delaying the launch."],
  tacit: ["There was a tacit agreement never to mention it."],
  astute: ["It was an astute reading of a very confusing market."],
  innocuous: ["What began as an innocuous remark ended in a row."],
  arduous: ["The climb was more arduous than the guidebook suggested."],
  redundant: ["Half the paragraph is redundant and can be cut.", "En inglés británico también «despedido»: to be made redundant."],
  lucid: ["Even at ninety, his prose remained perfectly lucid."],
  volatile: ["Energy prices have been volatile since the spring."],
  succinct: ["Keep the summary succinct: two paragraphs at most."],
  prudent: ["It would be prudent to wait for the final figures."],
  resilient: ["The local economy proved remarkably resilient."],
  inherent: ["There is an inherent risk in any pilot study.", "inherent IN sth."],
  ambiguous: ["The wording is ambiguous and invites two readings."],
  coherent: ["The government has yet to produce a coherent strategy."],
  feasible: ["Is it feasible to finish the analysis by June?"],
  scarce: ["Reliable data on the period is scarce."],
  stagnant: ["Wages have been stagnant for over a decade."],
  vigilant: ["Reviewers must remain vigilant for fabricated citations."],
  profound: ["The discovery had a profound effect on the field.", "«Profundo» físico es «deep»; «profound» es abstracto."],
  inevitable: ["A second round of cuts now looks inevitable."],
  sporadic: ["There has been sporadic fighting along the border."],
  rigorous: ["The study applies rigorous statistical controls."],
  detrimental: ["Long hours are detrimental to the quality of the work.", "detrimental TO sth."],
  pervasive: ["The influence of the school is pervasive but rarely acknowledged."],
  compelling: ["She presents a compelling argument for reform.", "También «absorbente»: a compelling novel."],
  mundane: ["Most of the job consists of mundane administrative tasks.", "No es «mundano» de vida social: es rutinario y anodino."],
  austere: ["The building has an austere, almost forbidding facade."],
  florid: ["His florid prose style has not aged well."],
  brazen: ["It was a brazen attempt to rewrite the record."],
  languid: ["They spent a languid afternoon by the river."],
  taciturn: ["Her supervisor was famously taciturn in meetings."],
  garrulous: ["A garrulous neighbour cornered him for an hour."],
  obstinate: ["He remained obstinate despite all the evidence."],
  amenable: ["The committee proved amenable to a compromise.", "amenable TO sth."],
  ephemeral: ["Online fame tends to be ephemeral."],
  intrepid: ["An intrepid few carried on despite the weather."],
  soporific: ["The lecture had a distinctly soporific effect."],
  truculent: ["He gave a truculent reply and left the room.", "Es «agresivo, belicoso», no «truculento» (gruesome)."],
  perfunctory: ["The inspection was perfunctory at best."],
  trenchant: ["She offered a trenchant critique of the methodology."],
  assiduous: ["Years of assiduous archival work lie behind the book."],
  inscrutable: ["His expression remained inscrutable throughout."],
  ostensible: ["The ostensible reason was budgetary, but nobody believed it.", "Implica que la razón real es otra."],
  recalcitrant: ["A handful of recalcitrant members blocked the vote."],

  /* --- falsos amigos --- */
  actually: ["It looks expensive, but it was actually quite cheap.", "«Actualmente» se dice «currently» o «at present»."],
  eventually: ["After three rejections, the paper was eventually accepted.", "«Eventualmente» (por casualidad) sería «possibly» u «occasionally»."],
  sensible: ["Taking an umbrella was the sensible thing to do.", "«Sensible» (emocionalmente) es «sensitive»."],
  sympathetic: ["My supervisor was sympathetic when I explained the delay.", "«Simpático» es «nice» o «friendly»."],
  argument: ["They had a bitter argument about the authorship.", "Vale para discusión y para argumento; el contexto decide."],
  advertisement: ["The advertisement ran in three national papers.", "«Advertencia» es «warning»."],
  attend: ["Over four hundred delegates attended the conference.", "Transitivo: attend a meeting, sin «to». «Atender a alguien» es «to see to sb»."],
  realize: ["I didn't realize the deadline had already passed.", "«Realizar» una tarea es «to carry out» o «to do»."],
  assist: ["Two technicians assisted with the setup.", "«Asistir a un evento» es «to attend»."],
  resume: ["Talks will resume on Monday.", "«Resumir» es «to summarise»."],
  pretend: ["He pretended not to have seen the email.", "«Pretender» es «to intend» o «to aim»."],
  support: ["The union supported the strike from the outset.", "«Soportar» algo molesto es «to put up with» o «to bear»."],
  library: ["The library holds a complete run of the journal.", "«Librería» (tienda) es «bookshop» o «bookstore»."],
  carpet: ["They laid a new carpet in the reading room.", "«Carpeta» es «folder»."],
  fabric: ["The dress is made of a lightweight fabric.", "«Fábrica» es «factory». También «the fabric of society»."],
  constipated: ["The medication can leave you constipated.", "«Constipado» (resfriado) es «to have a cold»."],
};
