/* Una frase de ejemplo (y nota cuando hace falta) para cada palabra del vocabulario.
   Formato: palabra: [frase en inglés, nota opcional en español, traducción de la frase al español] */

export const EXAMPLES = {
  /* ===== ACADÉMICAS FRECUENTES ===== */
  consultation: ["The policy was drafted in consultation with local residents.", "in consultation with = de acuerdo con, tras consultar a.", "La normativa se redactó de mutuo acuerdo con los vecinos del barrio."],
  conclusively: ["Nothing in the data proves conclusively that the drug works.", "", "Ninguno de los datos aportados demuestra a ciencia cierta que el medicamento funcione."],
  disruptive: ["Streaming proved far more disruptive to the industry than anyone predicted.", "", "El streaming revolucionó el sector muchísimo más de lo que nadie se esperaba."],
  intolerable: ["The working conditions in the warehouse were frankly intolerable.", "", "Las condiciones de trabajo en el almacén eran del todo insoportables."],
  immune: ["Nobody is immune to flattery, however rational they claim to be.", "immune TO. Preposición dependiente.", "Nadie se libra de la adulación, por muy racional que diga ser."],
  reckless: ["He was charged with reckless driving after the accident.", "", "Fue acusado de conducción temeraria tras el accidente."],
  offspring: ["The birds feed their offspring for several weeks after hatching.", "Invariable en plural: no existe offsprings.", "Los pájaros alimentan a sus crías durante varias semanas tras salir del cascarón."],
  strive: ["Small publishers strive to compete with the major chains.", "strive FOR sth / strive TO do sth.", "Las pequeñas editoriales hacen lo imposible por competir con las grandes cadenas."],
  thereafter: ["She left in 1998 and rarely returned thereafter.", "Registro formal, típico de textos legales y académicos.", "Se marchó en 1998 y, a partir de entonces, rara vez volvió."],
  scramble: ["Ministers scrambled to contain the damage after the leak.", "También revolver: scrambled eggs.", "Los ministros corrieron a apagar el fuego para contener los daños tras la filtración."],
  underway: ["Renovation work is already underway on the east wing.", "Se escribe junto cuando va con be.", "Las obras de reforma del ala este ya están en marcha."],
  strategically: ["The cameras were placed strategically around the perimeter.", "", "Las cámaras se colocaron estratégicamente por todo el perímetro."],
  scattered: ["Papers were scattered across every surface in the office.", "", "Había papeles esparcidos por todas las superficies de la oficina."],
  remorse: ["He showed not a flicker of remorse during the trial.", "Incontable: no remorse, nunca a remorse.", "No mostró ni el más mínimo remordimiento en todo el juicio."],
  complimentary: ["Guests receive a complimentary breakfast.", "Dos sentidos: gratuito y elogioso. No confundir with complimentary (complementario).", "El desayuno está incluido por cortesía de la casa."],
  additive: ["The label lists three artificial additives.", "", "En la etiqueta vienen indicados tres aditivos artificiales."],
  burial: ["The burial took place quietly, without press.", "", "El entierro se celebró en la intimidad, sin presencia de la prensa."],
  blunt: ["To be blunt, the manuscript is not ready.", "También romo: a blunt knife.", "Hablando en plata, el borrador todavía no está listo."],
  totalitarian: ["The novel imagines life under a totalitarian regime.", "", "La novela retrata cómo es la vida bajo un régimen totalitario."],
  arbitrary: ["The selection process seemed completely arbitrary to the candidates.", "Implica falta de lógica o sistema.", "El proceso de selección les pareció un sinsentido total a los candidatos."],
  complacency: ["A dangerous complacency had set in among the regulators before the crash.", "complacency ABOUT sth.", "Un exceso de confianza muy peligroso se había apoderado de los reguladores antes de la crisis."],
  unprecedented: ["The storm caused unprecedented damage to the coastal towns.", "", "La tormenta causó destrozos sin precedentes en los pueblos de la costa."],
  scrutiny: ["The company's accounts came under intense public scrutiny.", "", "Las cuentas de la empresa pasaron a ser examinadas con lupa por el público."],
  discrepancy: ["There is a significant discrepancy between the two sets of figures.", "discrepancy BETWEEN / discrepancy IN.", "Hay una diferencia abismal entre ambos grupos de cifras."],
  rationale: ["The report fails to explain the rationale behind the decision.", "", "El informe no aclara cuál es la lógica de fondo detrás de esa decisión."],
  tangible: ["The investment has produced tangible results for local communities.", "", "La inversión ha traído mejoras reales para la gente de la zona."],
  discern: ["It was difficult to discern any pattern in the data.", "", "Era complicadísimo ver algún patrón claro en los datos."],
  alleviate: ["New medication was prescribed to alleviate the chronic pain.", "alleviate pain / suffering / a problem.", "Le recetaron un nuevo medicamento para calmar el dolor crónico."],
  exacerbate: ["The drought was exacerbated by years of poor water management.", "exacerbate = make worse. Formal.", "La sequía empeoró aún más debido a años de una gestión nefasta del agua."],
  mitigate: ["Measures were taken to mitigate the environmental impact.", "mitigate the impact / risk / damage.", "Se tomaron medidas para reducir al mínimo el impacto ambiental."],

  /* ===== REGISTRO ALTO ===== */
  heinous: ["The court described the attack as a heinous crime.", "Se pronuncia /heɪnəs/, no hei-nious.", "El tribunal calificó el ataque como un crimen atroz."],
  pensive: ["She fell pensive when the subject came up.", "", "Se quedó pensativa cuando salió el tema."],
  pristine: ["The manuscript survived in pristine condition.", "", "El manuscrito sobrevivió en perfecto estado."],
  zealous: ["He was a zealous defender of the old rules.", "Ojo con el matiz: puede sonar a exceso de celo.", "Defendía las antiguas normas a capa y espada."],
  quaint: ["They stayed in a quaint cottage on the coast.", "Cuidado: aplicado a ideas puede ser condescendiente.", "Se alojaron en una casita con mucho encanto en la costa."],
  eloquent: ["Her closing statement was unusually eloquent.", "", "Su discurso de clausura fue de una elocuencia fuera de lo común."],
  swarthy: ["The portrait shows a swarthy, weather-beaten sailor.", "Literario y algo anticuado; úsalo solo en comprensión.", "El retrato muestra a un marinero de piel oscura, curtido por la intemperie."],
  lozenge: ["He sucked a throat lozenge through the whole meeting.", "", "Se pasó toda la reunión chupando un caramelo para la garganta."],
  alabaster: ["The tomb is carved from a single block of alabaster.", "", "La tumba está tallada en un único bloque de alabastro."],
  obfuscate: ["The report seems designed to obfuscate rather than explain.", "Implica ocultar a propósito, no simplemente confundir.", "El informe parece hecho para liar las cosas en vez de explicarlas."],
  prevaricate: ["Stop prevaricating and give me a straight answer.", "FALSO AMIGO: es andarse con evasivas, no prevaricar (que sería to pervert the course of justice).", "Deja de andarte con rodeos y dame una respuesta clara."],
  burble: ["A stream burbled somewhere below the path.", "", "Un arroyo murmuraba colina abajo."],
  fustigate: ["Editorials fustigated the government for its inaction.", "Muy formal y raro; casi solo aparece en textos de examen.", "Los editoriales atacaron sin piedad al gobierno por cruzarse de brazos."],
  impetuous: ["His impetuous decision to resign left the whole team in chaos.", "", "Su decisión impulsiva de dimitir sumió a todo el equipo en el caos."],
  mendacious: ["The inquiry revealed a systematic pattern of mendacious reporting.", "", "La investigación destapó un patrón sistemático de informes falsos."],
  laconic: ["His reply was characteristically laconic: just two words.", "laconic = brevísimo y directo. Contrario de garrulous.", "Su respuesta fue escueta como de costumbre: solo dos palabras."],
  fastidious: ["She was fastidious about hygiene in the laboratory.", "fastidious ABOUT sth.", "Era extremadamente meticulosa con la higiene en el laboratorio."],
  sycophantic: ["The reviews were so sycophantic that nobody trusted them.", "", "Las críticas eran tan pelotas que nadie se las creía."],
  magnanimous: ["It was magnanimous of him to forgive his rivals so publicly.", "", "Fue todo un detalle por su parte perdonar a sus rivales en público."],
  vociferous: ["The policy attracted vociferous opposition from local residents.", "", "La medida se topó con la rotunda oposición de los vecinos."],
  benevolent: ["The foundation was set up by a benevolent patron of the arts.", "", "La fundación nació gracias a un generoso mecenas."],
  inveterate: ["She is an inveterate traveller; she rarely spends two weeks in one place.", "", "Es una viajera empedernida; rara vez pasa dos semanas en el mismo sitio."],
  ostentatious: ["He had an ostentatious mansion that he rarely visited.", "", "Tenía un casoplón ostentoso en el que casi nunca ponía un pie."],
  reticent: ["He was reticent about his past and never discussed his childhood.", "reticent ABOUT sth. Diferente de reluctant (que tiene to + infinitivo).", "Era muy reservado con su pasado y nunca hablaba de su infancia."],
  veracious: ["I have every reason to believe the witness is veracious.", "", "Tengo motivos de sobra para creer que el testigo dice la verdad."],
  inimical: ["Such a hostile working environment is inimical to creativity.", "inimical TO sth = harmful to.", "Un ambiente de trabajo tan hostil mata por completo la creatividad."],
  propitious: ["The signs were propitious for a successful negotiation.", "propitious = favourable circumstances.", "Las señales eran muy favorables para llegar a buen puerto en la negociación."],
  querulous: ["After the operation, he became querulous and difficult to please.", "", "Tras la operación, se volvió un quejumbroso al que nada le parecía bien."],
  dispassionate: ["We need a dispassionate assessment of the facts, not an emotional one.", "", "Necesitamos analizar los hechos de manera fría y objetiva, sin dejarnos llevar por las emociones."],
  pernicious: ["The pernicious effects of poverty extend across generations.", "", "Las secuelas dañinas de la pobreza se arrastran de generación en generación."],

  /* ===== AMPLIACIÓN DE REGISTRO ===== */
  ubiquitous: ["Smartphones are now ubiquitous in classrooms.", "", "Los móviles están ya por todas partes en las aulas."],
  tenuous: ["The link between the two events is tenuous at best.", "", "La relación entre ambos sucesos está cogida con pinzas."],
  meticulous: ["He kept meticulous records of every transaction.", "", "Llevaba un registro milimétrico de cada transacción."],
  opaque: ["The funding rules remain opaque to most applicants.", "Se usa mucho en sentido figurado: difícil de entender.", "Las normas para pedir financiación siguen siendo indescifrables para la mayoría."],
  candid: ["In a candid interview, she admitted the project had failed.", "No confundir con cándido (naive).", "En una entrevista sin tapujos, reconoció que el proyecto había fracasado."],
  plausible: ["That is a plausible explanation, but it isn't proven.", "", "Es una explicación que se sostiene, pero no está demostrada."],
  cogent: ["She made a cogent case for delaying the launch.", "", "Presentó argumentos de peso a favor de retrasar el lanzamiento."],
  tacit: ["There was a tacit agreement never to mention it.", "", "Había un pacto de silencio para no sacar nunca el tema."],
  astute: ["It was an astute reading of a very confusing market.", "", "Fue un análisis muy astuto de un mercado de lo más confuso."],
  innocuous: ["What began as an innocuous remark ended in a row.", "", "Lo que empezó como un comentario inofensivo acabó en bronca."],
  arduous: ["The climb was more arduous than the guidebook suggested.", "", "La subida fue mucho más dura de lo que ponía en la guía."],
  redundant: ["Half the paragraph is redundant and can be cut.", "En inglés británico también despedido: to be made redundant.", "La mitad del párrafo sobra y se puede quitar directamente."],
  lucid: ["Even at ninety, his prose remained perfectly lucid.", "", "Incluso a los noventa años, su prosa seguía siendo sumamente clara."],
  volatile: ["Energy prices have been volatile since the spring.", "", "Los precios de la energía andan de lo más inestables desde la primavera."],
  succinct: ["Keep the summary succinct: two paragraphs at most.", "", "Resume al grano: dos párrafos como mucho."],
  prudent: ["It would be prudent to wait for the final figures.", "", "Lo más prudente sería esperar a tener las cifras definitivas."],
  resilient: ["The local economy proved remarkably resilient.", "", "La economía de la zona demostró tener una capacidad de aguante asombrosa."],
  inherent: ["There is an inherent risk in any pilot study.", "inherent IN sth.", "Cualquier estudio piloto conlleva un riesgo de por sí."],
  ambiguous: ["The wording is ambiguous and invites two readings.", "", "La redacción es ambigua y da pie a dos interpretaciones."],
  coherent: ["The government has yet to produce a coherent strategy.", "", "El gobierno todavía no ha sido capaz de armar una estrategia coherente."],
  feasible: ["Is it feasible to finish the analysis by June?", "", "¿Es viable terminar el análisis para antes de junio?"],
  scarce: ["Reliable data on the period is scarce.", "", "Apenas hay datos fiables sobre esa época."],
  stagnant: ["Wages have been stagnant for over a decade.", "", "Los salarios llevan congelados más de una década."],
  vigilant: ["Reviewers must remain vigilant for fabricated citations.", "", "Los revisores deben andar con mil ojos para detectar citas inventadas."],
  profound: ["The discovery had a profound effect on the field.", "Profundo físico es deep; profound es abstracto.", "El descubrimiento supuso un antes y un después en este campo."],
  inevitable: ["A second round of cuts now looks inevitable.", "", "Una segunda ronda de recortes parece ya inevitable."],
  sporadic: ["There has been sporadic fighting along the border.", "", "Ha habido choques aislados a lo largo de la frontera."],
  rigorous: ["The study applies rigorous statistical controls.", "", "El estudio cuenta con unos controles estadísticos superestrictos."],
  detrimental: ["Long hours are detrimental to the quality of the work.", "detrimental TO sth.", "Echar demasiadas horas perjudica seriamente la calidad del trabajo."],
  pervasive: ["The influence of the school is pervasive but rarely acknowledged.", "", "La influencia de la escuela se respira en todos lados, aunque rara vez se admita."],
  compelling: ["She presents a compelling argument for reform.", "También absorbente: a compelling novel.", "Presenta argumentos de peso a favor de la reforma."],
  mundane: ["Most of the job consists of mundane administrative tasks.", "No es mundano de vida social: es rutinario y anodino.", "La mayor parte del trabajo son simples tareas de oficina bastante rutinarias."],
  austere: ["The building has an austere, almost forbidding facade.", "", "El edificio tiene una fachada sobria y casi imponente."],
  florid: ["His florid prose style has not aged well.", "", "Su prosa tan recargada ha envejecido bastante mal."],
  brazen: ["It was a brazen attempt to rewrite the record.", "", "Fue un descarado intento de falsear el historial."],
  languid: ["They spent a languid afternoon by the river.", "", "Pasaron una tarde de lo más relajada junto al río."],
  taciturn: ["Her supervisor was famously taciturn in meetings.", "", "Su supervisora era conocida por no abrir la boca en las reuniones."],
  garrulous: ["A garrulous neighbour cornered him for an hour.", "", "Un vecino de lo más hablador lo acorraló durante una hora entera."],
  obstinate: ["He remained obstinate despite all the evidence.", "", "Se cerró en banda a pesar de tener todas las pruebas delante."],
  amenable: ["The committee proved amenable to a compromise.", "amenable TO sth.", "El comité se mostró dispuesto a llegar a un acuerdo."],
  ephemeral: ["Online fame tends to be ephemeral.", "", "La fama en internet suele ser flor de un día."],
  intrepid: ["An intrepid few carried on despite the weather.", "", "Unos cuantos valientes siguieron adelante a pesar del mal tiempo."],
  soporific: ["The lecture had a distinctly soporific effect.", "", "La charla tuvo un efecto soberanamente aburrido."],
  truculent: ["He gave a truculent reply and left the room.", "Es agresivo, belicoso, no truculento (gruesome).", "Soltó una contestación de malos modos y se marchó del cuarto."],
  perfunctory: ["The inspection was perfunctory at best.", "", "La inspección fue superficial, por no decir inútil."],
  trenchant: ["She offered a trenchant critique of the methodology.", "", "Lanzó una crítica demoledora contra la metodología utilizada."],
  assiduous: ["Years of assiduous archival work lie behind the book.", "", "El libro es el resultado de años de un minucioso trabajo de archivo."],
  inscrutable: ["His expression remained inscrutable throughout.", "", "Su cara no transmitía absolutamente nada durante todo el rato."],
  ostensible: ["The ostensible reason was budgetary, but nobody believed it.", "Implica que la razón real es otra.", "La excusa oficial fue el presupuesto, pero nadie se lo tragó."],
  recalcitrant: ["A handful of recalcitrant members blocked the vote.", "", "Unos pocos miembros rebeldes bloquearon la votación."],

  /* ===== FALSOS AMIGOS ===== */
  actually: ["It looks expensive, but it was actually quite cheap.", "Actualmente se dice currently o at present.", "Parece caro, pero en realidad estuvo tirado de precio."],
  eventually: ["After three rejections, the paper was eventually accepted.", "Eventualmente (por casualidad) sería possibly u occasionally.", "Tras tres rechazos, al final consiguieron que les aceptaran el artículo."],
  sensible: ["Taking an umbrella was the sensible thing to do.", "Sensible (emocionalmente) es sensitive.", "Llevarse un paraguas era lo más sensato."],
  sympathetic: ["My supervisor was sympathetic when I explained the delay.", "Simpático es nice o friendly.", "Mi supervisora se portó supercomprensiva cuando le conté por qué me había retrasado."],
  argument: ["They had a bitter argument about the authorship.", "Vale para discusión y para argumento; el contexto decide.", "Tuvieron una bronca monumental por el tema de la autoría."],
  advertisement: ["The advertisement ran in three national papers.", "Advertencia es warning.", "El anuncio salió en tres periódicos nacionales."],
  attend: ["Over four hundred delegates attended the conference.", "Transitivo: attend a meeting, sin to. Atender a alguien es to see to sb.", "Más de cuatrocientos delegados asistieron al congreso."],
  realize: ["I didn't realize the deadline had already passed.", "Realizar una tarea es to carry out o to do.", "No caí en la cuenta de que ya se había pasado el plazo."],
  assist: ["Two technicians assisted with the setup.", "Asistir a un evento es to attend.", "Dos técnicos echaron una mano con el montaje."],
  resume: ["Talks will resume on Monday.", "Resumir es to summarise.", "Las conversaciones se retomarán el lunes."],
  pretend: ["He pretended not to have seen the email.", "Pretender es to intend o to aim.", "Hizo como que no había visto el correo."],
  support: ["The union supported the strike from the outset.", "Soportar algo molesto es to put up with o to bear.", "El sindicato apoyó la huelga desde el primer momento."],
  library: ["The library holds a complete run of the journal.", "Librería (tienda) es bookshop o bookstore.", "La biblioteca conserva la colección entera de la revista."],
  carpet: ["They laid a new carpet in the reading room.", "Carpeta es folder.", "Pusieron una alfombra nueva en la sala de lectura."],
  fabric: ["The dress is made of a lightweight fabric.", "Fábrica es factory. También the fabric of society.", "El vestido está confeccionado con una tela muy ligera."],
  constipated: ["The medication can leave you constipated.", "Constipado (resfriado) es to have a cold.", "Este medicamento puede acabar estreñiéndote."],
  comprehensive: ["The committee carried out a comprehensive review of the system.", "Comprensivo (tolerante) es understanding.", "El comité hizo una revisión a fondo del sistema."],
  embarrassed: ["She was deeply embarrassed by the misunderstanding.", "Embarazada es pregnant.", "Se moría de la vergüenza por el malentendido."],
  deception: ["The whole plan was based on deception from the start.", "Decepción es disappointment.", "Todo el plan fue un engaño de principio a fin."],
  disgusted: ["He was disgusted by the state of the building.", "Disgustado (enfadado) es annoyed o upset.", "Le dio un asco tremendo ver cómo estaba el edificio."],
  ingenious: ["It was an ingenious solution to a complex problem.", "Ingenuo es naive.", "Fue una solución brillante para un problema enrevesado."],
  notorious: ["The area was notorious for its high crime rate.", "Notorio (bien conocido) es well-known o renowned.", "El barrio tenía una fama pésima por su alta delincuencia."],

  /* ===== PHRASAL VERBS — MOVIMIENTO Y ACCIÓN ===== */
  "bring about": ["The new policies brought about significant changes in the sector.", "Sinónimos formales: give rise to, result in, trigger.", "Las nuevas políticas trajeron consigo cambios significativos en el sector."],
  "bring forward": ["The meeting has been brought forward to Tuesday.", "Contrario: put back / postpone.", "Han adelantado la reunión al martes."],
  "bring off": ["It was a difficult negotiation, but she brought it off.", "Sinónimo: pull off, manage to achieve.", "Era una negociación complicada, pero ella consiguió sacarla adelante."],
  "bring up": ["Nobody wanted to bring up the subject of redundancies.", "También: raise a child.", "Nadie quería sacar a relucir el tema de los despidos."],
  "call for": ["The situation calls for urgent and decisive action.", "call for = require, demand.", "La situación exige tomar cartas en el asunto de manera urgente."],
  "call off": ["The outdoor concert was called off due to heavy rain.", "Sinónimo: cancel, abandon.", "Cancelaron el concierto al aire libre por culpa de las fuertes lluvias."],
  "carry out": ["The scientists are carrying out a series of complex experiments.", "", "Los científicos están llevando a cabo una serie de experimentos complejos."],
  "come across": ["She came across as very confident at the interview.", "También: come across a document = find by chance.", "En la entrevista dio la impresión de ser una persona muy segura de sí misma."],
  "come about": ["How exactly did this misunderstanding come about?", "Sinónimo: occur, happen, arise.", "¿Cómo se originó exactamente este malentendido?"],
  "come up with": ["The team came up with a brilliant solution.", "Sinónimo: devise, think up, propose.", "El equipo dio con una solución brillante."],
  "come to terms with": ["He has finally come to terms with the loss.", "Sinónimo: accept, reconcile oneself to.", "Por fin ha asimilado y superado la pérdida."],
  "die out": ["Several species of bird have died out in the last century.", "Sinónimo: become extinct.", "Varias especies de aves se han extinguido en el último siglo."],
  "fall apart": ["The coalition began to fall apart under the pressure.", "Sinónimo: disintegrate, collapse.", "La coalición empezó a desmoronarse por la presión."],
  "fall back on": ["When all else fails, we can fall back on our contingency plan.", "Sinónimo: resort to as a last option.", "Cuando todo lo demás falle, siempre podemos recurrir a nuestro plan de contingencia."],
  "fall through": ["The deal fell through at the last minute.", "Sinónimo: fail, not materialise.", "El trato se fue al traste en el último momento."],
  "get across": ["He struggled to get his point across to the committee.", "Sinónimo: communicate successfully.", "Le costó hacer llegar su punto de vista al comité."],
  "get around to": ["I never seem to get around to answering my emails.", "Expresar que por fin se hace algo que se dejaba para después.", "Nunca encuentro el momento de ponerme a responder los correos."],
  "get away with": ["She somehow got away with submitting the work late.", "Implica evitar las consecuencias de algo.", "De alguna manera se fue de rositas a pesar de entregar el trabajo tarde."],
  "get over": ["It took months to get over the shock of the news.", "Sinónimo: recover from.", "Tardó meses en digerir el shock de la noticia."],
  "give in": ["After lengthy negotiations, the company gave in to demands.", "Sinónimo: yield, concede, back down.", "Tras largas negociaciones, la empresa cedió a las exigencias."],
  "give rise to": ["The new findings give rise to several important questions.", "Sinónimo formal: bring about, generate.", "Los nuevos hallazgos dan pie a varias preguntas importantes."],
  "give way to": ["Traditional methods have gradually given way to digital ones.", "Sinónimo: be replaced by, yield to.", "Los métodos tradicionales han ido dejando paso a los digitales."],
  "go through with": ["Despite her doubts, she decided to go through with the plan.", "Sinónimo: carry out, follow through.", "A pesar de sus dudas, decidió seguir adelante con el plan."],
  "hold back": ["She held back her tears with great difficulty.", "Sinónimo: restrain, suppress.", "Contuvo las lágrimas a duras penas."],
  "hold out": ["The defenders managed to hold out for three more weeks.", "También: hold out hope = mantener la esperanza.", "Los defensores consiguieron resistir tres semanas más."],
  "keep up with": ["It's impossible to keep up with all the changes in legislation.", "Sinónimo: stay abreast of, remain current with.", "Es imposible estar al día de todos los cambios en las leyes."],
  "let down": ["The project let everyone down by missing every deadline.", "Sinónimo: disappoint, fail sb.", "El proyecto nos dejó a todos tirados al incumplir todos los plazos."],
  "look into": ["The board agreed to look into the allegations.", "Sinónimo: investigate, examine, probe.", "La junta acordó investigar las acusaciones."],
  "make up for": ["Extra practice can make up for a lack of natural talent.", "Sinónimo: compensate for.", "Echarle más horas puede compensar la falta de talento natural."],
  "phase out": ["The government plans to phase out coal plants by 2035.", "Sinónimo: gradually eliminate, discontinue.", "El gobierno planea retirar progresivamente las centrales de carbón antes de 2035."],
  "pick up on": ["A good editor will pick up on even the subtlest inconsistencies.", "Sinónimo: notice, detect, identify.", "Un buen editor detectará al vuelo la más mínima incoherencia."],
  "pull off": ["They pulled off a remarkable victory against the odds.", "Sinónimo: bring off, achieve something difficult.", "Consiguieron una victoria alucinante contra todo pronóstico."],
  "put across": ["The advertising campaign failed to put its message across.", "Sinónimo: communicate, convey.", "La campaña publicitaria no consiguió calar ni transmitir su mensaje."],
  "put forward": ["Several interesting proposals were put forward at the summit.", "Sinónimo: propose, suggest, advance.", "En la cumbre se pusieron sobre la mesa varias propuestas interesantes."],
  "put off": ["The press conference was put off until further notice.", "También: put sb off = discourage.", "La rueda de prensa se pospuso hasta nuevo aviso."],
  "rule out": ["The police have not ruled out the possibility of foul play.", "Sinónimo: exclude, eliminate.", "La policía no ha descartado la posibilidad de que haya gato encerrado."],
  "run out of": ["We have completely run out of time for further amendments.", "Siempre con complemento.", "Nos hemos quedado sin tiempo para añadir más enmiendas."],
  "set aside": ["Please set aside any personal feelings and focus on the facts.", "También: set aside funds = reserve money.", "Por favor, deja a un lado lo personal y céntrate en los hechos."],
  "set back": ["The strike set back the construction schedule by six months.", "Sinónimo: delay, hinder.", "La huelga retrasó las obras unos seis meses."],
  "set out": ["The report sets out a clear framework for future action.", "También: set out on a journey.", "El informe establece una hoja de ruta clara para dar los siguientes pasos."],
  "stand for": ["I won't stand for that kind of behaviour.", "También: abbreviation stands for = representa.", "No pienso tolerar ese tipo de comportamiento."],
  "stand out": ["Her thesis stood out from the rest because of its originality.", "", "Su tesis destacó de largo sobre las demás por su originalidad."],
  "take on": ["She was reluctant to take on any additional responsibilities.", "También: take on a competitor = challenge.", "Era reacia a echarse más responsabilidades a la espalda."],
  "take over": ["A rival firm has taken over the company.", "Sinónimo: assume control, acquire.", "Una empresa de la competencia se ha hecho con el control de la compañía."],
  "turn out": ["The scheme turned out to be more expensive than expected.", "Sinónimo: prove to be, result.", "El plan resultó salir más caro de lo que se esperaba."],
  "wear off": ["The effects of the anaesthetic began to wear off.", "Sinónimo: fade, diminish gradually.", "Los efectos de la anestesia empezaron a pasarse."],
  "work out": ["Things didn't work out as planned.", "También: solve a problem / do exercise.", "Las cosas no salieron como estaban previstas."],

  /* ===== PHRASAL VERBS — COMUNICACIÓN Y PENSAMIENTO ===== */
  "account for": ["He was asked to account for the missing funds.", "También: tourism accounts for 10% of GDP = representar.", "Se le pidió que explicara el porqué del dinero que faltaba."],
  "back up": ["Could you back up your argument with some data?", "También: make a copy of a file.", "¿Podrías respaldar lo que dices con algunos datos?"],
  "bear out": ["The survey results bear out our initial predictions.", "Sinónimo: confirm, corroborate.", "Los resultados de la encuesta confirman nuestras predicciones iniciales."],
  "build on": ["This paper builds on the work of earlier researchers.", "Sinónimo: develop further, extend.", "Este artículo toma como punto de partida el trabajo de investigadores anteriores."],
  "cast doubt on": ["The new evidence casts serious doubt on the original verdict.", "Sinónimo: challenge, undermine.", "Las nuevas pruebas ponen seriamente en duda el veredicto original."],
  "draw on": ["The novel draws heavily on the author's personal experiences.", "Sinónimo: use as a source, exploit.", "La novela se nutre en gran medida de las vivencias del propio autor."],
  "dwell on": ["There is no point in dwelling on past mistakes.", "Sinónimo: linger over, ruminate on.", "No sirve de nada comerse la cabeza con los errores del pasado."],
  "enlarge on": ["Could you enlarge on that point for the committee?", "Sinónimo: expand on, elaborate on.", "¿Podría profundizar más en ese punto ante el comité?"],
  "expand on": ["I'd like to expand on the third point of my argument.", "Sinónimo: elaborate, develop further.", "Me gustaría desarrollar más a fondo el tercer punto de mi exposición."],
  "gloss over": ["The report glosses over several serious weaknesses.", "Sinónimo: minimise, skip over, downplay.", "El informe pasa de puntillas por varios fallos graves."],
  "hammer out": ["After days of talks, the parties finally hammered out an agreement.", "Sinónimo: reach through effort.", "Tras días de negociaciones, las partes lograron por fin cerrar un acuerdo."],
  "hark back to": ["Her style harks back to the golden age of cinema.", "= recall/evoke an earlier time.", "Su estilo recuerda a la época dorada del cine."],
  "hinge on": ["Everything hinges on the outcome of this crucial vote.", "Sinónimo: depend on, turn on.", "Todo pende de un hilo y depende de esta votación tan importante."],
  "lay out": ["The plan lays out a three-stage process for implementation.", "Sinónimo: present, set out, explain.", "El plan detalla los tres pasos a seguir para su puesta en marcha."],
  "leave out": ["Several key facts were left out of the original report.", "Sinónimo: omit, exclude.", "Se pasaron por alto varios datos clave en el informe original."],
  "lend itself to": ["The data does not easily lend itself to straightforward analysis.", "Sinónimo: be suitable for.", "Los datos no se prestan precisamente a un análisis sencillo."],
  "pass off as": ["He tried to pass off the copied work as his own original research.", "Sinónimo: present fraudulently as.", "Intentó colar el trabajo copiado como si fuera una investigación original suya."],
  "point out": ["The auditors pointed out several irregularities in the accounts.", "Sinónimo: draw attention to, highlight.", "Los auditores sacaron a la luz varias irregularidades en las cuentas."],
  "put down to": ["The improvement can be put down to the new management strategy.", "Sinónimo: attribute to.", "La mejora se debe a la nueva estrategia de gestión."],
  "put up with": ["I refuse to put up with such unprofessional behaviour.", "Sinónimo: tolerate, endure.", "Me niego en redondo a aguantar una falta de profesionalidad semejante."],
  "run through": ["Let me run through the main points once more.", "Sinónimo: summarise, go over quickly.", "Dejadme dar un repaso rápido a los puntos principales una vez más."],
  "see through": ["He saw through her excuse immediately.", "También: see through a project = complete it.", "Le caló la excusa al instante."],
  "single out": ["She was singled out for special praise in the report.", "Sinónimo: select, distinguish, pick out.", "El informe la destacó especialmente para aplaudir su labor."],
  "spell out": ["The consequences need to be spelled out very clearly.", "Sinónimo: explain in detail, state explicitly.", "Hay que explicar las consecuencias con pelos y señales."],
  "stem from": ["Many of the problems stem from a lack of proper communication.", "Sinónimo: originate in, arise from.", "Muchos problemas vienen de no hablar las cosas como es debido."],
  "sum up": ["To sum up, the evidence points firmly towards reform.", "Sinónimo: summarise, conclude.", "En pocas palabras, las pruebas dejan claro que hace falta una reforma."],
  "throw light on": ["The new documents throw considerable light on the events.", "Sinónimo: shed light on, clarify.", "Los nuevos documentos aclaran notablemente cómo ocurrieron los hechos."],
  "touch on": ["The report only touches on the issue of long-term sustainability.", "Sinónimo: mention briefly, refer to.", "El informe pasa muy por encima por el tema de la viabilidad a largo plazo."],
  "write off": ["The investment was written off after two years.", "También: dismiss, consider worthless.", "La inversión se dio totalmente por perdida al cabo de dos años."],

  /* ===== IDIOMS C1/C2 ===== */
  "take sth in one's stride": ["She took the critical feedback completely in her stride.", "= accept without being upset or flustered.", "Se tomó las críticas con total filosofía, sin inmutarse."],
  "fly in the face of": ["His claim flies in the face of all available evidence.", "= contradict openly.", "Su teoría choca de frente con todas las pruebas disponibles."],
  "on the grounds that": ["The application was rejected on the grounds that the budget was insufficient.", "= on the basis that, because.", "La solicitud fue rechazada con la excusa de que el presupuesto no daba para más."],
  "for all intents and purposes": ["The project is, for all intents and purposes, finished.", "= in every practical sense.", "El proyecto está prácticamente terminado a falta de algún fleco."],
  "at odds with": ["His version of events is at odds with the other witnesses'.", "= in conflict with.", "Su versión no cuadra para nada con la de los demás testigos."],
  "in the wake of": ["New regulations were introduced in the wake of the financial crisis.", "= as a consequence of, following.", "Se introdujeron nuevas normas a raíz de la crisis financiera."],
  "on the verge of": ["The company was on the verge of collapse when they found new investors.", "= on the point of, about to.", "La empresa estaba a punto de quebrar cuando aparecieron nuevos inversores."],
  "to bear fruit": ["Their months of research are finally beginning to bear fruit.", "= produce positive results.", "Tantos meses de investigación están empezando a dar sus frutos."],
  "to take a toll on": ["The long commute was taking a serious toll on her health.", "= have a negative effect on.", "Tener que viajar tanto a diario le estaba pasando factura a la salud."],
  "to fall short of": ["The results fell well short of what the board had expected.", "= not reach, be insufficient.", "Los resultados se quedaron muy por debajo de las expectativas de la junta."],
  "to draw a line under": ["It's time to draw a line under the whole affair and move on.", "= bring to an end, put behind you.", "Es hora de pasar página de una vez y mirar hacia delante."],
  "to turn a blind eye to": ["The management turned a blind eye to the safety violations.", "= deliberately ignore.", "La dirección hizo la vista gorda ante las fallas de seguridad."],
  "to give the benefit of the doubt": ["I'll give you the benefit of the doubt just this once.", "= trust despite uncertainty.", "Te daré el beneficio de la duda, pero que sea la última vez."],
  "once and for all": ["We need to settle this matter once and for all.", "= finally and definitively.", "Tenemos que zanjar este asunto de una vez por todas."],
  "out of the blue": ["She resigned out of the blue, with no warning whatsoever.", "= suddenly and unexpectedly.", "Dimitió de la noche a la mañana y sin avisar a nadie."],
  "above board": ["The auditors confirmed that all transactions were completely above board.", "= transparent, honest, legal.", "Los auditores confirmaron que todas las cuentas estaban limpias y eran transparentes."],
  "to sit on the fence": ["Politicians can't sit on the fence when it comes to climate policy.", "= refuse to take sides.", "Los políticos no pueden andarse con medias tintas ante el cambio climático."],
  "to bite the bullet": ["We had to bite the bullet and accept the terms.", "= endure something painful.", "No nos quedó otra que tragar saliva y aceptar las condiciones."],
  "to cut corners": ["The contractor cut corners on materials, with disastrous results.", "= do something poorly to save money or time.", "El contratista escatimó en materiales y la cosa acabó en desastre."],
  "to get the upper hand": ["The defendant's counsel quickly got the upper hand in the cross-examination.", "= gain an advantage.", "El abogado defensor acorraló al testigo y tomó la delantera."],
  "to go hand in hand with": ["Innovation and risk go hand in hand with entrepreneurship.", "= are naturally associated.", "Innovar y arriesgar van siempre de la mano al emprender."],
  "to keep a low profile": ["After the scandal, she kept a very low profile for months.", "= avoid drawing attention to oneself.", "Tras el escándalo, mantuvo un perfil muy bajo durante meses."],
  "to leave no stone unturned": ["The investigators left no stone unturned in their search for the truth.", "= try every possible option.", "Los investigadores removieron cielo y tierra para dar con la verdad."],
  "to lose sight of": ["We must not lose sight of the original aims of the project.", "= forget, fail to keep in mind.", "No debemos perder el norte sobre los objetivos iniciales del proyecto."],
  "to make headway": ["Despite the obstacles, the team is slowly making headway.", "= make progress.", "Pese a las trabas, el equipo va avanzando poco a poco."],
  "to paint a grim picture": ["The report paints a grim picture of the industry's future.", "= describe pessimistically.", "El informe pinta un panorama muy negro para el futuro del sector."],
  "to play devil's advocate": ["Let me play devil's advocate and suggest the opposite view.", "= argue the opposite to stimulate debate.", "Déjame hacer de abogado del diablo y plantear la postura contraria."],
  "to put sth into perspective": ["This graph puts the statistics into perspective very clearly.", "= see in proper context.", "Este gráfico ayuda a entender bien qué significan estas estadísticas."],
  "to shed light on": ["The new evidence sheds light on how the accident occurred.", "= clarify, explain.", "Las nuevas pruebas arrojan algo de luz sobre cómo ocurrió el accidente."],
  "to speak volumes": ["His silence on the matter speaks volumes.", "= reveal a great deal implicitly.", "Su silencio dice más que mil palabras."],
  "to stand the test of time": ["Her novels have truly stood the test of time.", "= remain valued over many years.", "Sus novelas han envejecido de maravilla y siguen vigentes hoy en día."],
  "to strike a balance": ["It is difficult to strike the right balance between freedom and security.", "= achieve an equilibrium.", "Cuesta encontrar un equilibrio justo entre libertad y seguridad."],
  "to take precedence over": ["Safety considerations take precedence over financial ones.", "= be more important than.", "La seguridad está por encima del dinero."],
  "to tip the balance": ["That final piece of evidence tipped the balance in the jury's decision.", "= be the decisive factor.", "Esa última prueba fue la que acabó decantando la balanza para el jurado."],
  "to weather the storm": ["The company managed to weather the economic storm.", "= survive a difficult period.", "La empresa logró capear el temporal económico."],
  "a double-edged sword": ["Social media is a double-edged sword: it connects and isolates.", "= something with both advantages and disadvantages.", "Las redes sociales son un arma de doble filo: te conectan y a la vez te aíslan."],
  "a far cry from": ["The finished product was a far cry from what had been promised.", "= very different from.", "El producto final no tenía nada que ver con lo que nos habían prometido."],
  "a mixed blessing": ["Working from home has proved to be a mixed blessing for many.", "= something good that has disadvantages too.", "Para muchos, teletrabajar ha resultado ser una de cal y otra de arena."],
  "at the expense of": ["Growth was achieved at the expense of workers' rights.", "= causing harm to.", "El crecimiento se consiguió recortando los derechos de los trabajadores."],
  "by the same token": ["If we accept that argument, we must, by the same token, accept its implications.", "= in the same way, equally.", "Si aceptamos ese argumento, del mismo modo debemos asumir sus consecuencias."],
  "in the long run": ["In the long run, investing in education always pays off.", "= eventually, over time.", "A la larga, invertir en educación siempre sale a cuenta."],
  "in no uncertain terms": ["She told them in no uncertain terms that the behaviour was unacceptable.", "= very clearly and firmly.", "Les dejó bien clarito que ese comportamiento era intolerable."],
  "on a par with": ["The quality of this research is on a par with the best in the field.", "= at the same level as.", "La calidad de esta investigación no tiene nada que envidiar a las mejores."],
  "to have a vested interest in": ["The pharmaceutical companies have a vested interest in prolonging patent protection.", "= to benefit personally from.", "Las farmacéuticas tienen intereses creados para que las patentes duren más."],
  "to pave the way for": ["The peace treaty paved the way for economic cooperation.", "= make possible, prepare the conditions for.", "El tratado de paz allanó el camino para la cooperación económica."],
  "to break new ground": ["The study breaks new ground in our understanding of early language acquisition.", "= be pioneering, do something for the first time.", "El estudio abre un camino totalmente nuevo para entender cómo aprenden a hablar los niños."],

  /* ===== CRIMEN Y DERECHO ===== */
  accomplice: ["The getaway driver was charged as an accomplice to the robbery.", "accomplice IN a crime / TO a crime.", "El conductor de la huida fue acusado como cómplice del robo."],
  acquit: ["The jury acquitted him of all charges.", "acquit sb OF sth. Contrario: convict.", "El jurado lo absolvió de todos los cargos."],
  allegation: ["The minister denied all the allegations.", "allegation OF sth / allegation THAT.", "El ministro negó todas las acusaciones."],
  arson: ["The fire investigators concluded that arson was the cause.", "arsonist = persona que lo comete.", "Los investigadores de incendios concluyeron que el fuego intencionado fue la causa."],
  bail: ["He was released on bail pending trial.", "on bail = en libertad bajo fianza.", "Fue puesto en libertad bajo fianza a la espera del juicio."],
  bribery: ["He was found guilty of bribery and corruption.", "bribe (verb/noun), bribery (noun).", "Fue declarado culpable de soborno y corrupción."],
  burglary: ["The house had been broken into: it was a professional burglary.", "burglar = ladrón de casas.", "Habían forzado la entrada: fue un robo con allanamiento profesional."],
  clemency: ["The prisoner appealed to the governor for clemency.", "show clemency = be lenient/merciful.", "El preso apeló al gobernador en busca de clemencia."],
  collusion: ["There were clear signs of collusion between the two companies.", "in collusion WITH.", "Había claros indicios de colusión entre las dos empresas."],
  conviction: ["His conviction was later overturned on appeal.", "También: deep conviction = firme creencia.", "Su condena fue posteriormente anulada en apelación."],
  culpable: ["The report concluded that both parties were culpable.", "culpable NEGLIGENCE = negligencia culpable.", "El informe concluyó que ambas partes eran culpables."],
  deterrent: ["The threat of heavy fines acts as a strong deterrent.", "act as a deterrent TO crime.", "La amenaza de cuantiosas multas actúa como un fuerte elemento disuasorio."],
  embezzlement: ["He was charged with the embezzlement of pension funds.", "embezzle (verb).", "Fue acusado de malversación de fondos de pensiones."],
  extortion: ["She was blackmailed and forced to pay extortion money.", "extort (verb).", "Fue chantajeada y obligada a pagar dinero extorsionado."],
  fraud: ["The bank discovered a sophisticated fraud involving fake accounts.", "", "El banco descubrió un sofisticado fraude relacionado con cuentas falsas."],
  grievance: ["The union tabled a list of grievances to be addressed.", "lodge / air a grievance.", "El sindicato presentó una lista de quejas para que se abordaran."],
  indict: ["He was indicted on three counts of tax evasion.", "indict sb FOR / ON charges.", "Fue procesado por tres cargos de evasión fiscal."],
  incarceration: ["He faced five years of incarceration.", "incarcerate (verb).", "Se enfrentaba a cinco años de encarcelamiento."],
  jurisdiction: ["The crime falls outside our jurisdiction.", "within / outside the jurisdiction OF.", "El delito queda fuera de nuestra jurisdicción."],
  larceny: ["He was convicted of petty larceny.", "Grand larceny / petty larceny.", "Fue condenado por hurto menor."],
  manslaughter: ["She pleaded guilty to manslaughter rather than murder.", "Involuntary manslaughter = without intent.", "Se declaró culpable de homicidio imprudente en lugar de asesinato."],
  misconduct: ["The doctor was struck off following findings of serious professional misconduct.", "", "El médico fue inhabilitado tras constatarse una grave conducta profesional indebida."],
  perpetrator: ["The perpetrators were never brought to justice.", "perpetrate (verb).", "Los perpetradores nunca fueron llevados ante la justicia."],
  prosecution: ["The prosecution presented overwhelming evidence.", "prosecution (acusación), defense (defensa).", "La acusación presentó pruebas abrumadoras."],
  sentence: ["He was given a ten-year prison sentence.", "sentence sb TO sth.", "Le impusieron una pena de diez años de prisión."],
  smuggling: ["Customs officers seized a large smuggling operation.", "smuggle (verb), smuggler.", "Los agentes de aduanas desmantelaron una gran operación de contrabando."],
  testimony: ["Her testimony was crucial to the outcome of the trial.", "give testimony / testimony OF.", "Su testimonio fue crucial para el resultado del juicio."],
  vandalism: ["Acts of vandalism damaged several historic monuments.", "vandal, vandalise.", "Actos de vandalismo dañaron varios monumentos históricos."],
  verdict: ["The jury returned a verdict of not guilty.", "reach / return a verdict.", "El jurado emitió un veredicto de no culpabilidad."],

  /* ===== CIENCIA Y TECNOLOGÍA ===== */
  algorithm: ["The search engine uses a complex algorithm to rank results.", "algorithmic (adj).", "El motor de búsqueda utiliza un algoritmo complejo para clasificar los resultados."],
  autonomous: ["Autonomous vehicles could reduce road accidents significantly.", "autonomy (noun).", "Los vehículos autónomos podrían reducir significativamente los accidentes de tráfico."],
  breakthrough: ["The discovery represents a major breakthrough in cancer research.", "make / achieve a breakthrough.", "El descubrimiento representa un avance importante en la investigación del cáncer."],
  calibrate: ["The instruments must be carefully calibrated before use.", "calibration (noun).", "Los instrumentos deben calibrarse cuidadosamente antes de su uso."],
  catalyst: ["The report acted as a catalyst for sweeping reform.", "catalyst FOR change.", "El informe actuó como catalizador de una reforma de gran alcance."],
  cognition: ["The study explores the role of emotion in human cognition.", "cognitive (adj).", "El estudio explora el papel de la emoción en la cognición humana."],
  corroborate: ["The DNA evidence corroborated the witness's account.", "corroborating evidence.", "La evidencia de ADN corroboró la declaración del testigo."],
  empirical: ["The theory is supported by a wealth of empirical data.", "empirically (adv).", "La teoría está respaldada por una gran cantidad de datos empíricos."],
  hypothesis: ["The hypothesis was tested under strict laboratory conditions.", "plural: hypotheses.", "La hipótesis fue probada bajo estrictas condiciones de laboratorio."],
  innate: ["Language acquisition appears to be an innate human capacity.", "innately (adv).", "La adquisición del lenguaje parece ser una capacidad humana innata."],
  iterate: ["The team iterated through dozens of prototypes before settling on a design.", "iteration (noun).", "El equipo pasó por docenas de prototipos antes de decidirse por un diseño."],
  paradigm: ["The discovery represented a paradigm shift in the field.", "paradigm shift = radical change of thinking.", "El descubrimiento representó un cambio de paradigma en el campo."],
  peer: ["The paper was subjected to rigorous peer review before publication.", "peer-reviewed journal.", "El artículo fue sometido a una rigurosa revisión por pares antes de su publicación."],
  prototype: ["They built a working prototype within six months.", "prototype (verb) = build a first model.", "Construyeron un prototipo funcional en seis meses."],
  replication: ["Replication of the original results proved impossible.", "replicate (verb).", "La replicación de los resultados originales resultó imposible."],
  synthesis: ["The essay provides a synthesis of current research in the field.", "synthesise (verb).", "El ensayo ofrece una síntesis de la investigación actual en el campo."],

  /* ===== LITERATURA Y ARTE ===== */
  allegory: ["The novel can be read as an allegory for political oppression.", "allegorical (adj).", "La novela puede leerse como una alegoría de la opresión política."],
  ambivalent: ["Critics were ambivalent about the film's rather bleak ending.", "ambivalence (noun).", "Los críticos mostraron ambivalencia ante el final bastante sombrío de la película."],
  anachronistic: ["The playwright's modern references felt slightly anachronistic.", "anachronism (noun).", "Las referencias modernas del dramaturgo resultaron ligeramente anacrónicas."],
  cathartic: ["Many people find tragedy cathartic rather than distressing.", "catharsis (noun).", "Muchas personas encuentran la tragedia catártica más que angustiosa."],
  cynical: ["His later work has a deeply cynical view of human nature.", "cynicism (noun).", "Su obra tardía tiene una visión profundamente cínica de la naturaleza humana."],
  depict: ["The painting depicts a scene from classical mythology.", "depiction (noun).", "La pintura representa una escena de la mitología clásica."],
  dystopian: ["The novel presents a chilling dystopian vision of the future.", "dystopia (noun).", "La novela presenta una escalofriante visión distópica del futuro."],
  enigmatic: ["The poem's ending remains enigmatic, inviting multiple interpretations.", "enigma (noun).", "El final del poema sigue siendo enigmático, invitando a múltiples interpretaciones."],
  evocative: ["The film's soundtrack is powerfully evocative of the 1950s.", "evoke (verb).", "La banda sonora de la película evoca poderosamente los años cincuenta."],
  harrowing: ["The harrowing final chapter left readers deeply shaken.", "harrowing = deeply distressing.", "El desgarrador capítulo final dejó a los lectores profundamente conmocionados."],
  idyllic: ["The opening chapter paints an idyllic picture of rural life.", "idyll (noun).", "El capítulo inicial pinta un cuadro idílico de la vida rural."],
  juxtapose: ["The exhibition juxtaposes photographs from different eras.", "juxtaposition (noun).", "La exposición yuxtapone fotografías de diferentes épocas."],
  melancholic: ["The final movement of the symphony has a deeply melancholic quality.", "melancholy (noun).", "El movimiento final de la sinfonía tiene una cualidad profundamente melancólica."],
  motif: ["The image of the sea serves as a central motif throughout the novel.", "leitmotif = recurring theme.", "La imagen del mar sirve como motivo central a lo largo de la novela."],
  nuanced: ["Her portrayal of the character is subtle and nuanced.", "nuance (noun).", "Su interpretación del personaje es sutil y matizada."],
  paradoxical: ["It is paradoxical that increased choice can lead to greater dissatisfaction.", "paradox (noun).", "Es paradójico que una mayor oferta pueda llevar a una mayor insatisfacción."],
  poignant: ["The final scene is both funny and deeply poignant.", "poignancy (noun).", "La escena final es a la vez divertida y profundamente emotiva."],
  satirical: ["The book is a satirical attack on the media and its obsession with celebrity.", "satire (noun).", "El libro es un ataque satírico a los medios de comunicación y su obsesión con la fama."],
  seminal: ["This is a seminal text in the field of critical theory.", "seminal = highly influential and original.", "Este es un texto seminal en el campo de la teoría crítica."],
  subversive: ["Her poetry was considered subversive by the authorities.", "subversion (noun).", "Sus poemas eran considerados subversivos por las autoridades."],
  symbolism: ["The use of water as symbolism is pervasive throughout the text.", "symbol, symbolic (adj).", "El uso del agua como simbolismo es omnipresente en todo el texto."],
  witty: ["The script is consistently witty without being cruel.", "wit (noun).", "El guion es consistentemente ingenioso sin ser cruel."],

  /* ===== VERBOS FORMALES ===== */
  contend: ["Some economists contend that the policy will backfire.", "contend THAT = sostener que.", "Algunos economistas sostienen que la política tendrá un efecto contrario al deseado."],
  assert: ["The report asserts that the figures have been independently verified.", "assertion (noun).", "El informe afirma que las cifras han sido verificadas de forma independiente."],
  demonstrate: ["The experiment demonstrates conclusively that the compound is stable.", "demonstration (noun).", "El experimento demuestra de forma concluyente que el compuesto es estable."],
  facilitate: ["The new platform facilitates collaboration between remote teams.", "facilitation (noun).", "La nueva plataforma facilita la colaboración entre equipos remotos."],
  trigger: ["The announcement triggered a sharp drop in share prices.", "trigger (also noun) = something that sets off a reaction.", "El anuncio desencadenó una fuerte caída en el precio de las acciones."],
  prompt: ["The new findings prompted an immediate review of the safety procedures.", "prompt (also adj = immediate, also noun = reminder).", "Los nuevos hallazgos motivaron una revisión inmediata de los procedimientos de seguridad."],
  ameliorate: ["Several measures were adopted to ameliorate the conditions.", "amelioration (noun). More formal than improve.", "Se adoptaron varias medidas para mejorar las condiciones."],
  necessitate: ["The scale of the project necessitates careful planning at every stage.", "necessitate = make necessary.", "La envergadura del proyecto requiere una planificación cuidadosa en cada etapa."],
  endeavour: ["The foundation endeavours to promote access to education worldwide.", "endeavour (also noun). British spelling; US: endeavor.", "La fundación se esfuerza por promover el acceso a la educación en todo el mundo."],
  utilise: ["The team utilised every available resource.", "utilise (British) / utilize (American). More formal than use.", "El equipo utilizó todos los recursos disponibles."],
  scrutinise: ["All contracts must be carefully scrutinised before signing.", "scrutiny (noun). British spelling; US: scrutinize.", "Todos los contratos deben examinarse cuidadosamente antes de firmarlos."],
  formulate: ["They spent weeks formulating a coherent response to the crisis.", "formulation (noun).", "Pasaron semanas formulando una respuesta coherente a la crisis."],

  /* ===== SOCIEDAD Y MEDIOS ===== */
  accountability: ["There must be greater accountability in public life.", "accountable FOR sth.", "Debe haber una mayor responsabilidad en la vida pública."],
  advocacy: ["She dedicated her career to advocacy for refugee rights.", "advocate (verb/noun).", "Dedicó su carrera a la defensa de los derechos de los refugiados."],
  backlash: ["The decision provoked a fierce backlash from consumer groups.", "a backlash AGAINST sth.", "La decisión provocó una fuerte reacción adversa por parte de los grupos de consumidores."],
  censorship: ["The film was subject to censorship before its release.", "censor (verb/noun).", "La película estuvo sujeta a censura antes de su estreno."],
  cohesion: ["Social cohesion is threatened by growing inequality.", "cohesive (adj).", "La cohesión social se ve amenazada por la creciente desigualdad."],
  consensus: ["There is broad consensus that reform is needed.", "reach / build a consensus ON sth.", "Hay un amplio consenso en que se necesita una reforma."],
  corruption: ["Anti-corruption measures are being strengthened.", "corrupt (adj/verb).", "Se están reforzando las medidas anticorrupción."],
  dissent: ["The bill was passed despite significant dissent.", "dissenter (noun), dissenting voice.", "El proyecto de ley fue aprobado a pesar de una disidencia considerable."],
  grassroots: ["The campaign was driven by grassroots activists.", "grassroots movement = popular, bottom-up.", "La campaña fue impulsada por activistas de base."],
  lobbyist: ["Lobbyists from the pharmaceutical industry met with the minister.", "lobby (verb/noun).", "Grupos de presión de la industria farmacéutica se reunieron con el ministro."],
  monopoly: ["The company holds a near-monopoly in this sector.", "monopolise (verb).", "La empresa tiene un cuasi-monopolio en este sector."],
  rhetoric: ["The politician's rhetoric was more convincing than her policy.", "rhetorical (adj), rhetorically.", "La retórica de la política era más convincente que su política real."],
  sovereignty: ["The issue of national sovereignty is central to the debate.", "sovereign (adj/noun).", "La cuestión de la soberanía nacional es central en el debate."],
  transparency: ["Voters are demanding greater transparency in political funding.", "transparent (adj).", "Los votantes exigen una mayor transparencia en la financiación política."],

  /* ===== VOCABULARIO DE NEGACIÓN ===== */
  "by no means": ["This is by no means a comprehensive account of all the evidence.", "Seguido de inversión al inicio de frase: By no means IS this...", "Esto no es de ninguna manera un relato exhaustivo de toda la evidencia."],
  "in no way": ["This finding is in no way conclusive.", "in no way = de ninguna manera.", "Este hallazgo no es de ninguna manera concluyente."],
  "on no account": ["On no account should the details be shared before publication.", "Inversión obligatoria: On no account SHOULD...", "En ningún caso deberían compartirse los detalles antes de la publicación."],
  "under no circumstances": ["Under no circumstances are visitors permitted in the laboratory.", "Inversión obligatoria al inicio de frase.", "Bajo ninguna circunstancia se permite la entrada de visitantes al laboratorio."],
  "at no point": ["At no point during the investigation were these facts disclosed.", "Inversión: At no point DID they disclose...", "En ningún momento de la investigación se revelaron estos hechos."],
  "to no avail": ["She called for help repeatedly, but to no avail.", "= without success.", "Pidió ayuda repetidamente, pero en vano."],
  "let alone": ["The office lacks basic supplies, let alone modern equipment.", "= and even less, much less.", "La oficina carece de suministros básicos, por no hablar de equipos modernos."],
  "nothing short of": ["The speed of the response was nothing short of remarkable.", "= truly, genuinely (emphatic).", "La velocidad de la respuesta fue verdaderamente notable."],
  "anything but": ["The transition was anything but smooth.", "= the opposite of, not at all.", "La transición no fue ni mucho menos fluida."],
  "far from": ["The results were far from satisfactory.", "far from + adj/noun = not at all.", "Los resultados estaban lejos de ser satisfactorios."],

  /* ===== EXPRESIONES DE GRADO Y CANTIDAD ===== */
  "a great deal of": ["A great deal of research still needs to be done.", "= a large amount of (with uncountable nouns).", "Todavía queda mucha investigación por hacer."],
  "a wide range of": ["The report covers a wide range of topics.", "= many different types.", "El informe abarca una amplia gama de temas."],
  "a host of": ["The policy has attracted a host of critics.", "= a large number of.", "La política ha atraído a un gran número de críticos."],
  "a handful of": ["Only a handful of participants completed the full study.", "= a small number, very few.", "Solo un puñado de participantes completó el estudio completo."],
  "the vast majority of": ["The vast majority of respondents supported the change.", "= nearly all.", "La gran mayoría de los encuestados apoyó el cambio."],
  "to a great extent": ["The crisis was, to a great extent, caused by regulatory failure.", "= largely, in large measure.", "La crisis fue, en gran medida, causada por un fallo regulatorio."],
  "to some extent": ["To some extent, the criticism is fair.", "= partly, in some ways.", "En cierta medida, la crítica es justa."],
  "by far": ["This is by far the most compelling argument in the paper.", "= by a large margin.", "Este es con mucho el argumento más convincente del artículo."],
  overwhelmingly: ["The proposal was overwhelmingly rejected by the committee.", "= by a very large majority.", "La propuesta fue rechazada abrumadoramente por el comité."],
  disproportionately: ["The cuts fell disproportionately on lower-income households.", "= in a way that is too large or too small compared to what is fair.", "Los recortes recayeron de forma desproporcionada en los hogares de menores ingresos."],
  exp  syringes: ["The nurse disposed of the used syringes in a sealed container.", "syringe (sing.) => syringes (pl.).", "La enfermera tiró las jeringuillas usadas a un contenedor cerrado."],
  aim: ["The aim of the study is to map how startups communicate visually.", "aim (n.) = goal/purpose; aim TO do sth (v.) = aspirar a.", "El estudio tiene como objetivo ver cómo se comunican visualmente las startups."],
  intricacies: ["Few outsiders grasp the intricacies of academic funding.", "the intricacies of = los entresijos de; solo se usa en plural.", "Pocos de fuera entienden realmente los entresijos de cómo funciona la financiación académica."],
  uninitiated: ["To the uninitiated, the jargon can seem impenetrable.", "Casi siempre en la frase fija: to the uninitiated = para los no iniciados.", "Para los que no están metidos en el mundillo, la jerga puede sonar a chino."],
  "sliding door": ["The flat has a sliding door onto the balcony.", "sliding door = puerta corredera; revolving door = puerta giratoria.", "El piso tiene una puerta corredera para salir al balcón."],
  ceiling: ["Rents have hit a ceiling in the city centre.", "ceiling = techo literal; glass ceiling = techo de cristal; wage ceiling = tope salarial.", "Los alquileres ya han tocado techo en el centro."],
  edge: ["Fluency in English gives you a clear edge over other candidates.", "have/gain an edge (over sb) = tener ventaja; on the edge of = al borde de.", "Dominar el inglés te da una ventaja tremenda frente a otros candidatos."],
  boundaries: ["The project pushes the boundaries of qualitative analysis.", "push/cross/blur the boundaries; cf. border (frontera política).", "El proyecto lleva al límite el análisis cualitativo."],
  border: ["They crossed the border at dawn.", "border = frontera política; cf. boundaries (límites conceptuales/personales).", "Cruzaron la frontera al amanecer."],
  vicinity: ["There are no pharmacies in the vicinity of the campus.", "in the vicinity of también = approximately: in the vicinity of 500 pounds.", "No hay ninguna farmacia cerca del campus."],
  reliable: ["The data come from a reliable source.", "reliable = fiable; reliability (n.); rely on (phrasal).", "Los datos proceden de una fuente totalmente fiable."],
  daunting: ["Writing a thesis can be daunting at first.", "a daunting task/prospect/challenge. Sinónimo: intimidating, overwhelming.", "Escribir una tesis puede dar bastante vértigo al principio."],
  "see fit to": ["Parliament saw fit to enact the reform without consultation.", "see fit to + infinitive = juzgar oportuno; tono formal, a menudo crítico o irónico.", "El Parlamento tuvo a bien aprobar la reforma sin consultar a nadie."],
  succeeding: ["In the succeeding years, the policy was quietly dropped.", "succeeding (adj.) = following, subsequent; NO confundir con succeed (v.) = tener éxito.", "En los años posteriores, la medida se fue dejando de lado discretamente."],
  supply: ["The supply of housing has not kept pace with demand.", "supply and demand; supply sth TO sb (v.); supplies (pl.) = suministros.", "La oferta de vivienda no ha ido a la par con la demanda."],
  arise: ["Several questions arose during the seminar.", "Intransitivo: arise FROM sth = surgir de algo. NUNCA arise a problem.", "Surgieron varias dudas durante el seminario."],
  "lead to": ["Poor sampling leads to unreliable conclusions.", "lead TO + noun/gerund; sinónimos: result in, give rise to, bring about.", "Un mal muestreo acaba llevando a conclusiones poco fiables."],
  retrace: ["She retraced her steps to find the missing key.", "retrace one's steps = desandar lo andado; retrace a route = reconstruirlo.", "Desandó el camino para buscar la llave perdida."],
  regress: ["Without practice, your speaking will regress.", "Connotación negativa: implica volver a un estado peor. regression (n.).", "Si no practicas, vas a perder soltura al hablar."],
  return: ["He returned to Madrid in June after a year abroad.", "return = volver/devolver (neutro); cf. retrace (desandar), regress (retroceder).", "Regresó a Madrid en junio tras pasar un año fuera."],

  /* ===== LÉXICO ADICIONAL Y AGRÍCOLA ===== */
  crop: ["Wheat is the country's main crop.", "", "El trigo es el cultivo principal del país."],
  harvest: ["The harvest was poor after the drought.", "harvest = la recolección o la cosecha recogida (n. y v.).", "La cosecha fue escasa por culpa de la sequía."],
  soil: ["The soil here is too sandy for olives.", "soil = tierra, suelo agrícola. No confundir con ground o floor.", "La tierra de aquí es demasiado arenosa para plantar olivos."],
  mulching: ["Mulching helps the soil retain water in summer.", "mulching = acolchado: cubrir la tierra con paja/materia orgánica.", "El acolchado ayuda a que la tierra conserve la humedad en verano."],
  cull: ["Thousands of birds were culled to contain the outbreak.", "cull = sacrificar selectivamente animales; descartar/entresacar.", "Sacrificaron a miles de aves para frenar el brote."],
  circumscribed: ["The role of the committee is narrowly circumscribed by statute.", "circumscribed = limitado, restringido, acotado.", "El papel del comité está muy acotado por los estatutos."],
  unyielding: ["The negotiator remained unyielding despite the pressure.", "unyielding = inflexible, que no cede.", "El negociador no dio su brazo a torcer a pesar de la presión."],
  fundamental: ["Trust is fundamental to any collaboration.", "fundamental TO something.", "La confianza es clave para trabajar en equipo."],
  unforeseen: ["The delay was caused by unforeseen circumstances.", "unforeseen = imprevisto.", "El retraso se debió a imprevistos de última hora."],
  "high in fat": ["This product is high in fat.", "high in + nutriente (low in sugar, high in fibre).", "Este producto tiene mucha grasa."],
  "eagerly awaited": ["Her eagerly awaited second novel comes out in May.", "eagerly awaited = esperado con ansia, muy esperado (colocación fija).", "Su esperadísima segunda novela saldrá a la venta en mayo."],
  loom: ["The thesis deadline looms.", "loom = cernerse, asomar de forma amenazante. loom large = pesar mucho.", "La fecha de entrega de la tesis ya asoma a la vuelta de la esquina."],
  postpone: ["The seminar has been postponed until October.", "postpone = aplazar.", "El seminario se ha aplazado hasta octubre."],
  "speed up": ["We need to speed up the production process.", "speed up = acelerar (informal).", "Tenemos que meterle prisa al proceso de producción."],
  streamline: ["The bank streamlined its approval process.", "streamline = simplificar y agilizar un proceso.", "El banco agilizó su proceso de aprobación de solicitudes."],
  "make loan approvals": ["The manager will make loan approvals on Friday.", "make loan approvals = tramitar/conceder aprobaciones de préstamos.", "El gerente firmará la aprobación de los préstamos el viernes."],
  peruse: ["I need time to peruse the contract before signing.", "peruse = leer con detenimiento, examinar a fondo (NO es hojear).", "Necesito tiempo para leerme el contrato con lupa antes de firmar."],
  "come in": ["The results came in late.", "come in = llegar (datos, resultados) / entrar / intervenir.", "Los resultados llegaron tarde."],
  warrant: ["The case warrants further study.", "como verbo: justificar o merecer; como sustantivo: orden judicial.", "El caso merece que se investigue más a fondo."],
  "run low": ["We're running low on funding.", "run low = quedarse sin, ir quedándose bajo de (run low on).", "Nos estamos quedando sin dinero."],
  "feel spent": ["After the viva, she felt completely spent.", "feel spent = sentirse agotado, exhausto.", "Tras la defensa de la tesis, se quedó completamente exhausta."],
  spare: ["Spare me the excuses.", "spare = ahorrar algo desagradable / spare me: ahórramelo, déjate de historias.", "Ahórrame los sermones."],
  glad: ["She was glad to go.", "glad = contento, alegre (solo predicativo: I am glad).", "Se alegró de irse."],
  "in the near term": ["Interest rates are unlikely to fall in the near term.", "in the near term = a corto plazo (contexto económico).", "Es poco probable que los tipos de interés bajen a corto plazo."],
  due: ["The report is due Friday.", "due = con fecha prevista, pendiente de entrega / debido a (due to).", "El informe hay que entregarlo el viernes."],
  dude: ["Hey dude, what's up?", "dude = tío, colega (slang estadounidense muy informal).", "Oye tío, ¿qué pasa?"],
};
