/* Una frase de ejemplo (y nota cuando hace falta) para cada palabra del vocabulario.
   Formato: palabra: [frase en inglés, nota opcional en español] */

export const EXAMPLES = {
  /* ===== ACADÉMICAS FRECUENTES ===== */
  consultation: ["The policy was drafted in consultation with local residents.", "in consultation with = de acuerdo con, tras consultar a."],
  conclusively: ["Nothing in the data proves conclusively that the drug works."],
  disruptive: ["Streaming proved far more disruptive to the industry than anyone predicted."],
  intolerable: ["The working conditions in the warehouse were frankly intolerable."],
  immune: ["Nobody is immune to flattery, however rational they claim to be.", "immune TO. Preposición dependiente."],
  reckless: ["He was charged with reckless driving after the accident."],
  offspring: ["The birds feed their offspring for several weeks after hatching.", "Invariable en plural: no existe «offsprings»."],
  strive: ["Small publishers strive to compete with the major chains.", "strive FOR sth / strive TO do sth."],
  thereafter: ["She left in 1998 and rarely returned thereafter.", "Registro formal, típico de textos legales y académicos."],
  scramble: ["Ministers scrambled to contain the damage after the leak.", "También «revolver»: scrambled eggs."],
  underway: ["Renovation work is already underway on the east wing.", "Se escribe junto cuando va con «be»."],
  strategically: ["The cameras were placed strategically around the perimeter."],
  scattered: ["Papers were scattered across every surface in the office."],
  remorse: ["He showed not a flicker of remorse during the trial.", "Incontable: «no remorse», nunca «a remorse»."],
  complimentary: ["Guests receive a complimentary breakfast.", "Dos sentidos: gratuito y elogioso. No confundir con «complementary» (complementario)."],
  additive: ["The label lists three artificial additives."],
  burial: ["The burial took place quietly, without press."],
  blunt: ["To be blunt, the manuscript is not ready.", "También «romo»: a blunt knife."],
  totalitarian: ["The novel imagines life under a totalitarian regime."],
  arbitrary: ["The selection process seemed completely arbitrary to the candidates.", "Implica falta de lógica o sistema: «at random»."],
  complacency: ["A dangerous complacency had set in among the regulators before the crash.", "complacency ABOUT sth."],
  unprecedented: ["The storm caused unprecedented damage to the coastal towns."],
  scrutiny: ["The company's accounts came under intense public scrutiny."],
  discrepancy: ["There is a significant discrepancy between the two sets of figures.", "discrepancy BETWEEN / discrepancy IN."],
  rationale: ["The report fails to explain the rationale behind the decision."],
  tangible: ["The investment has produced tangible results for local communities."],
  discern: ["It was difficult to discern any pattern in the data."],
  alleviate: ["New medication was prescribed to alleviate the chronic pain.", "alleviate pain / suffering / a problem."],
  exacerbate: ["The drought was exacerbated by years of poor water management.", "exacerbate = make worse. Formal."],
  mitigate: ["Measures were taken to mitigate the environmental impact.", "mitigate the impact / risk / damage."],

  /* ===== REGISTRO ALTO ===== */
  heinous: ["The court described the attack as a heinous crime.", "Se pronuncia /ˈheɪnəs/, no «hei-nious»."],
  pensive: ["She fell pensive when the subject came up."],
  pristine: ["The manuscript survived in pristine condition."],
  zealous: ["He was a zealous defender of the old rules.", "Ojo con el matiz: puede sonar a exceso de celo."],
  quaint: ["They stayed in a quaint cottage on the coast.", "Cuidado: aplicado a ideas puede ser condescendiente."],
  eloquent: ["Her closing statement was unusually eloquent."],
  swarthy: ["The portrait shows a swarthy, weather-beaten sailor.", "Literario y algo anticuado; úsalo solo en comprensión."],
  lozenge: ["He sucked a throat lozenge through the whole meeting."],
  alabaster: ["The tomb is carved from a single block of alabaster."],
  obfuscate: ["The report seems designed to obfuscate rather than explain.", "Implica ocultar a propósito, no simplemente confundir."],
  prevaricate: ["Stop prevaricating and give me a straight answer.", "FALSO AMIGO: es «andarse con evasivas», no «prevaricar» (que sería «to pervert the course of justice»)."],
  burble: ["A stream burbled somewhere below the path."],
  fustigate: ["Editorials fustigated the government for its inaction.", "Muy formal y raro; casi solo aparece en textos de examen."],
  impetuous: ["His impetuous decision to resign left the whole team in chaos."],
  mendacious: ["The inquiry revealed a systematic pattern of mendacious reporting."],
  laconic: ["His reply was characteristically laconic: just two words.", "laconic = brevísimo y directo. Contrario de garrulous."],
  fastidious: ["She was fastidious about hygiene in the laboratory.", "fastidious ABOUT sth."],
  sycophantic: ["The reviews were so sycophantic that nobody trusted them."],
  magnanimous: ["It was magnanimous of him to forgive his rivals so publicly."],
  vociferous: ["The policy attracted vociferous opposition from local residents."],
  benevolent: ["The foundation was set up by a benevolent patron of the arts."],
  inveterate: ["She is an inveterate traveller; she rarely spends two weeks in one place."],
  ostentatious: ["He had an ostentatious mansion that he rarely visited."],
  reticent: ["He was reticent about his past and never discussed his childhood.", "reticent ABOUT sth. Diferente de «reluctant» (que tiene «to + infinitivo»)."],
  veracious: ["I have every reason to believe the witness is veracious."],
  inimical: ["Such a hostile working environment is inimical to creativity.", "inimical TO sth = harmful to."],
  propitious: ["The signs were propitious for a successful negotiation.", "propitious = favourable circumstances."],
  querulous: ["After the operation, he became querulous and difficult to please."],
  dispassionate: ["We need a dispassionate assessment of the facts, not an emotional one."],
  pernicious: ["The pernicious effects of poverty extend across generations."],

  /* ===== AMPLIACIÓN DE REGISTRO ===== */
  ubiquitous: ["Smartphones are now ubiquitous in classrooms."],
  tenuous: ["The link between the two events is tenuous at best."],
  meticulous: ["He kept meticulous records of every transaction."],
  opaque: ["The funding rules remain opaque to most applicants.", "Se usa mucho en sentido figurado: difícil de entender."],
  candid: ["In a candid interview, she admitted the project had failed.", "No confundir con «cándido» (naive)."],
  plausible: ["That is a plausible explanation, but it isn't proven."],
  cogent: ["She made a cogent case for delaying the launch."],
  tacit: ["There was a tacit agreement never to mention it."],
  astute: ["It was an astute reading of a very confusing market."],
  innocuous: ["What began as an innocuous remark ended in a row."],
  arduous: ["The climb was more arduous than the guidebook suggested."],
  redundant: ["Half the paragraph is redundant and can be cut.", "En inglés británico también «despedido»: to be made redundant."],
  lucid: ["Even at ninety, his prose remained perfectly lucid."],
  volatile: ["Energy prices have been volatile since the spring."],
  succinct: ["Keep the summary succinct: two paragraphs at most."],
  prudent: ["It would be prudent to wait for the final figures."],
  resilient: ["The local economy proved remarkably resilient."],
  inherent: ["There is an inherent risk in any pilot study.", "inherent IN sth."],
  ambiguous: ["The wording is ambiguous and invites two readings."],
  coherent: ["The government has yet to produce a coherent strategy."],
  feasible: ["Is it feasible to finish the analysis by June?"],
  scarce: ["Reliable data on the period is scarce."],
  stagnant: ["Wages have been stagnant for over a decade."],
  vigilant: ["Reviewers must remain vigilant for fabricated citations."],
  profound: ["The discovery had a profound effect on the field.", "«Profundo» físico es «deep»; «profound» es abstracto."],
  inevitable: ["A second round of cuts now looks inevitable."],
  sporadic: ["There has been sporadic fighting along the border."],
  rigorous: ["The study applies rigorous statistical controls."],
  detrimental: ["Long hours are detrimental to the quality of the work.", "detrimental TO sth."],
  pervasive: ["The influence of the school is pervasive but rarely acknowledged."],
  compelling: ["She presents a compelling argument for reform.", "También «absorbente»: a compelling novel."],
  mundane: ["Most of the job consists of mundane administrative tasks.", "No es «mundano» de vida social: es rutinario y anodino."],
  austere: ["The building has an austere, almost forbidding facade."],
  florid: ["His florid prose style has not aged well."],
  brazen: ["It was a brazen attempt to rewrite the record."],
  languid: ["They spent a languid afternoon by the river."],
  taciturn: ["Her supervisor was famously taciturn in meetings."],
  garrulous: ["A garrulous neighbour cornered him for an hour."],
  obstinate: ["He remained obstinate despite all the evidence."],
  amenable: ["The committee proved amenable to a compromise.", "amenable TO sth."],
  ephemeral: ["Online fame tends to be ephemeral."],
  intrepid: ["An intrepid few carried on despite the weather."],
  soporific: ["The lecture had a distinctly soporific effect."],
  truculent: ["He gave a truculent reply and left the room.", "Es «agresivo, belicoso», no «truculento» (gruesome)."],
  perfunctory: ["The inspection was perfunctory at best."],
  trenchant: ["She offered a trenchant critique of the methodology."],
  assiduous: ["Years of assiduous archival work lie behind the book."],
  inscrutable: ["His expression remained inscrutable throughout."],
  ostensible: ["The ostensible reason was budgetary, but nobody believed it.", "Implica que la razón real es otra."],
  recalcitrant: ["A handful of recalcitrant members blocked the vote."],

  /* ===== FALSOS AMIGOS ===== */
  actually: ["It looks expensive, but it was actually quite cheap.", "«Actualmente» se dice «currently» o «at present»."],
  eventually: ["After three rejections, the paper was eventually accepted.", "«Eventualmente» (por casualidad) sería «possibly» u «occasionally»."],
  sensible: ["Taking an umbrella was the sensible thing to do.", "«Sensible» (emocionalmente) es «sensitive»."],
  sympathetic: ["My supervisor was sympathetic when I explained the delay.", "«Simpático» es «nice» o «friendly»."],
  argument: ["They had a bitter argument about the authorship.", "Vale para discusión y para argumento; el contexto decide."],
  advertisement: ["The advertisement ran in three national papers.", "«Advertencia» es «warning»."],
  attend: ["Over four hundred delegates attended the conference.", "Transitivo: attend a meeting, sin «to». «Atender a alguien» es «to see to sb»."],
  realize: ["I didn't realize the deadline had already passed.", "«Realizar» una tarea es «to carry out» o «to do»."],
  assist: ["Two technicians assisted with the setup.", "«Asistir a un evento» es «to attend»."],
  resume: ["Talks will resume on Monday.", "«Resumir» es «to summarise»."],
  pretend: ["He pretended not to have seen the email.", "«Pretender» es «to intend» o «to aim»."],
  support: ["The union supported the strike from the outset.", "«Soportar» algo molesto es «to put up with» o «to bear»."],
  library: ["The library holds a complete run of the journal.", "«Librería» (tienda) es «bookshop» o «bookstore»."],
  carpet: ["They laid a new carpet in the reading room.", "«Carpeta» es «folder»."],
  fabric: ["The dress is made of a lightweight fabric.", "«Fábrica» es «factory». También «the fabric of society»."],
  constipated: ["The medication can leave you constipated.", "«Constipado» (resfriado) es «to have a cold»."],
  comprehensive: ["The committee carried out a comprehensive review of the system.", "«Comprensivo» (tolerante) es «understanding»."],
  embarrassed: ["She was deeply embarrassed by the misunderstanding.", "«Embarazada» es «pregnant»."],
  deception: ["The whole plan was based on deception from the start.", "«Decepción» es «disappointment»."],
  disgusted: ["He was disgusted by the state of the building.", "«Disgustado» (enfadado) es «annoyed» o «upset»."],
  ingenious: ["It was an ingenious solution to a complex problem.", "«Ingenuo» es «naive»."],
  notorious: ["The area was notorious for its high crime rate.", "«Notorio» (bien conocido) es «well-known» o «renowned»."],

  /* ===== PHRASAL VERBS — MOVIMIENTO Y ACCIÓN ===== */
  "bring about": ["The new policies brought about significant changes in the sector.", "Sinónimos formales: give rise to, result in, trigger."],
  "bring forward": ["The meeting has been brought forward to Tuesday.", "Contrario: put back / postpone."],
  "bring off": ["It was a difficult negotiation, but she brought it off.", "Sinónimo: pull off, manage to achieve."],
  "bring up": ["Nobody wanted to bring up the subject of redundancies.", "También: raise a child."],
  "call for": ["The situation calls for urgent and decisive action.", "call for = require, demand."],
  "call off": ["The outdoor concert was called off due to heavy rain.", "Sinónimo: cancel, abandon."],
  "carry out": ["The scientists are carrying out a series of complex experiments."],
  "come across": ["She came across as very confident at the interview.", "También: come across a document = find by chance."],
  "come about": ["How exactly did this misunderstanding come about?", "Sinónimo: occur, happen, arise."],
  "come up with": ["The team came up with a brilliant solution.", "Sinónimo: devise, think up, propose."],
  "come to terms with": ["He has finally come to terms with the loss.", "Sinónimo: accept, reconcile oneself to."],
  "die out": ["Several species of bird have died out in the last century.", "Sinónimo: become extinct."],
  "fall apart": ["The coalition began to fall apart under the pressure.", "Sinónimo: disintegrate, collapse."],
  "fall back on": ["When all else fails, we can fall back on our contingency plan.", "Sinónimo: resort to as a last option."],
  "fall through": ["The deal fell through at the last minute.", "Sinónimo: fail, not materialise."],
  "get across": ["He struggled to get his point across to the committee.", "Sinónimo: communicate successfully."],
  "get around to": ["I never seem to get around to answering my emails.", "Expresar que por fin se hace algo que se dejaba para después."],
  "get away with": ["She somehow got away with submitting the work late.", "Implica evitar las consecuencias de algo."],
  "get over": ["It took months to get over the shock of the news.", "Sinónimo: recover from."],
  "give in": ["After lengthy negotiations, the company gave in to demands.", "Sinónimo: yield, concede, back down."],
  "give rise to": ["The new findings give rise to several important questions.", "Sinónimo formal: bring about, generate."],
  "give way to": ["Traditional methods have gradually given way to digital ones.", "Sinónimo: be replaced by, yield to."],
  "go through with": ["Despite her doubts, she decided to go through with the plan.", "Sinónimo: carry out, follow through."],
  "hold back": ["She held back her tears with great difficulty.", "Sinónimo: restrain, suppress."],
  "hold out": ["The defenders managed to hold out for three more weeks.", "También: hold out hope = mantener la esperanza."],
  "keep up with": ["It's impossible to keep up with all the changes in legislation.", "Sinónimo: stay abreast of, remain current with."],
  "let down": ["The project let everyone down by missing every deadline.", "Sinónimo: disappoint, fail sb."],
  "look into": ["The board agreed to look into the allegations.", "Sinónimo: investigate, examine, probe."],
  "make up for": ["Extra practice can make up for a lack of natural talent.", "Sinónimo: compensate for."],
  "phase out": ["The government plans to phase out coal plants by 2035.", "Sinónimo: gradually eliminate, discontinue."],
  "pick up on": ["A good editor will pick up on even the subtlest inconsistencies.", "Sinónimo: notice, detect, identify."],
  "pull off": ["They pulled off a remarkable victory against the odds.", "Sinónimo: bring off, achieve something difficult."],
  "put across": ["The advertising campaign failed to put its message across.", "Sinónimo: communicate, convey."],
  "put forward": ["Several interesting proposals were put forward at the summit.", "Sinónimo: propose, suggest, advance."],
  "put off": ["The press conference was put off until further notice.", "También: put sb off = discourage."],
  "rule out": ["The police have not ruled out the possibility of foul play.", "Sinónimo: exclude, eliminate."],
  "run out of": ["We have completely run out of time for further amendments.", "Siempre con complemento."],
  "set aside": ["Please set aside any personal feelings and focus on the facts.", "También: set aside funds = reserve money."],
  "set back": ["The strike set back the construction schedule by six months.", "Sinónimo: delay, hinder."],
  "set out": ["The report sets out a clear framework for future action.", "También: set out on a journey."],
  "stand for": ["I won't stand for that kind of behaviour.", "También: abbreviation stands for = representa."],
  "stand out": ["Her thesis stood out from the rest because of its originality."],
  "take on": ["She was reluctant to take on any additional responsibilities.", "También: take on a competitor = challenge."],
  "take over": ["A rival firm has taken over the company.", "Sinónimo: assume control, acquire."],
  "turn out": ["The scheme turned out to be more expensive than expected.", "Sinónimo: prove to be, result."],
  "wear off": ["The effects of the anaesthetic began to wear off.", "Sinónimo: fade, diminish gradually."],
  "work out": ["Things didn't work out as planned.", "También: solve a problem / do exercise."],

  /* ===== PHRASAL VERBS — COMUNICACIÓN Y PENSAMIENTO ===== */
  "account for": ["He was asked to account for the missing funds.", "También: tourism accounts for 10% of GDP = representar."],
  "back up": ["Could you back up your argument with some data?", "También: make a copy of a file."],
  "bear out": ["The survey results bear out our initial predictions.", "Sinónimo: confirm, corroborate."],
  "build on": ["This paper builds on the work of earlier researchers.", "Sinónimo: develop further, extend."],
  "cast doubt on": ["The new evidence casts serious doubt on the original verdict.", "Sinónimo: challenge, undermine."],
  "draw on": ["The novel draws heavily on the author's personal experiences.", "Sinónimo: use as a source, exploit."],
  "dwell on": ["There is no point in dwelling on past mistakes.", "Sinónimo: linger over, ruminate on."],
  "enlarge on": ["Could you enlarge on that point for the committee?", "Sinónimo: expand on, elaborate on."],
  "expand on": ["I'd like to expand on the third point of my argument.", "Sinónimo: elaborate, develop further."],
  "gloss over": ["The report glosses over several serious weaknesses.", "Sinónimo: minimise, skip over, downplay."],
  "hammer out": ["After days of talks, the parties finally hammered out an agreement.", "Sinónimo: reach through effort."],
  "hark back to": ["Her style harks back to the golden age of cinema.", "= recall/evoke an earlier time. No confundir con 'hark back' y 'hearken to'."],
  "hinge on": ["Everything hinges on the outcome of this crucial vote.", "Sinónimo: depend on, turn on."],
  "lay out": ["The plan lays out a three-stage process for implementation.", "Sinónimo: present, set out, explain."],
  "leave out": ["Several key facts were left out of the original report.", "Sinónimo: omit, exclude."],
  "lend itself to": ["The data does not easily lend itself to straightforward analysis.", "Sinónimo: be suitable for."],
  "pass off as": ["He tried to pass off the copied work as his own original research.", "Sinónimo: present fraudulently as."],
  "point out": ["The auditors pointed out several irregularities in the accounts.", "Sinónimo: draw attention to, highlight."],
  "put down to": ["The improvement can be put down to the new management strategy.", "Sinónimo: attribute to."],
  "put up with": ["I refuse to put up with such unprofessional behaviour.", "Sinónimo: tolerate, endure."],
  "run through": ["Let me run through the main points once more.", "Sinónimo: summarise, go over quickly."],
  "see through": ["He saw through her excuse immediately.", "También: see through a project = complete it."],
  "single out": ["She was singled out for special praise in the report.", "Sinónimo: select, distinguish, pick out."],
  "spell out": ["The consequences need to be spelled out very clearly.", "Sinónimo: explain in detail, state explicitly."],
  "stem from": ["Many of the problems stem from a lack of proper communication.", "Sinónimo: originate in, arise from."],
  "sum up": ["To sum up, the evidence points firmly towards reform.", "Sinónimo: summarise, conclude."],
  "throw light on": ["The new documents throw considerable light on the events.", "Sinónimo: shed light on, clarify."],
  "touch on": ["The report only touches on the issue of long-term sustainability.", "Sinónimo: mention briefly, refer to."],
  "write off": ["The investment was written off after two years.", "También: dismiss, consider worthless."],

  /* ===== IDIOMS C1/C2 ===== */
  "take sth in one's stride": ["She took the critical feedback completely in her stride.", "= accept without being upset or flustered."],
  "fly in the face of": ["His claim flies in the face of all available evidence.", "= contradict openly."],
  "on the grounds that": ["The application was rejected on the grounds that the budget was insufficient.", "= on the basis that, because."],
  "for all intents and purposes": ["The project is, for all intents and purposes, finished.", "= in every practical sense."],
  "at odds with": ["His version of events is at odds with the other witnesses'.", "= in conflict with."],
  "in the wake of": ["New regulations were introduced in the wake of the financial crisis.", "= as a consequence of, following."],
  "on the verge of": ["The company was on the verge of collapse when they found new investors.", "= on the point of, about to."],
  "to bear fruit": ["Their months of research are finally beginning to bear fruit.", "= produce positive results."],
  "to take a toll on": ["The long commute was taking a serious toll on her health.", "= have a negative effect on."],
  "to fall short of": ["The results fell well short of what the board had expected.", "= not reach, be insufficient."],
  "to draw a line under": ["It's time to draw a line under the whole affair and move on.", "= bring to an end, put behind you."],
  "to turn a blind eye to": ["The management turned a blind eye to the safety violations.", "= deliberately ignore."],
  "to give the benefit of the doubt": ["I'll give you the benefit of the doubt just this once.", "= trust despite uncertainty."],
  "once and for all": ["We need to settle this matter once and for all.", "= finally and definitively."],
  "out of the blue": ["She resigned out of the blue, with no warning whatsoever.", "= suddenly and unexpectedly."],
  "above board": ["The auditors confirmed that all transactions were completely above board.", "= transparent, honest, legal."],
  "to sit on the fence": ["Politicians can't sit on the fence when it comes to climate policy.", "= refuse to take sides."],
  "to bite the bullet": ["We had to bite the bullet and accept the terms.", "= endure something painful."],
  "to cut corners": ["The contractor cut corners on materials, with disastrous results.", "= do something poorly to save money or time."],
  "to get the upper hand": ["The defendant's counsel quickly got the upper hand in the cross-examination.", "= gain an advantage."],
  "to go hand in hand with": ["Innovation and risk go hand in hand with entrepreneurship.", "= are naturally associated."],
  "to keep a low profile": ["After the scandal, she kept a very low profile for months.", "= avoid drawing attention to oneself."],
  "to leave no stone unturned": ["The investigators left no stone unturned in their search for the truth.", "= try every possible option."],
  "to lose sight of": ["We must not lose sight of the original aims of the project.", "= forget, fail to keep in mind."],
  "to make headway": ["Despite the obstacles, the team is slowly making headway.", "= make progress."],
  "to paint a grim picture": ["The report paints a grim picture of the industry's future.", "= describe pessimistically."],
  "to play devil's advocate": ["Let me play devil's advocate and suggest the opposite view.", "= argue the opposite to stimulate debate."],
  "to put sth into perspective": ["This graph puts the statistics into perspective very clearly.", "= see in proper context."],
  "to shed light on": ["The new evidence sheds light on how the accident occurred.", "= clarify, explain."],
  "to speak volumes": ["His silence on the matter speaks volumes.", "= reveal a great deal implicitly."],
  "to stand the test of time": ["Her novels have truly stood the test of time.", "= remain valued over many years."],
  "to strike a balance": ["It is difficult to strike the right balance between freedom and security.", "= achieve an equilibrium."],
  "to take precedence over": ["Safety considerations take precedence over financial ones.", "= be more important than."],
  "to tip the balance": ["That final piece of evidence tipped the balance in the jury's decision.", "= be the decisive factor."],
  "to weather the storm": ["The company managed to weather the economic storm.", "= survive a difficult period."],
  "a double-edged sword": ["Social media is a double-edged sword: it connects and isolates.", "= something with both advantages and disadvantages."],
  "a far cry from": ["The finished product was a far cry from what had been promised.", "= very different from."],
  "a mixed blessing": ["Working from home has proved to be a mixed blessing for many.", "= something good that has disadvantages too."],
  "at the expense of": ["Growth was achieved at the expense of workers' rights.", "= causing harm to."],
  "by the same token": ["If we accept that argument, we must, by the same token, accept its implications.", "= in the same way, equally."],
  "in the long run": ["In the long run, investing in education always pays off.", "= eventually, over time."],
  "in no uncertain terms": ["She told them in no uncertain terms that the behaviour was unacceptable.", "= very clearly and firmly."],
  "on a par with": ["The quality of this research is on a par with the best in the field.", "= at the same level as."],
  "to have a vested interest in": ["The pharmaceutical companies have a vested interest in prolonging patent protection.", "= to benefit personally from."],
  "to pave the way for": ["The peace treaty paved the way for economic cooperation.", "= make possible, prepare the conditions for."],
  "to break new ground": ["The study breaks new ground in our understanding of early language acquisition.", "= be pioneering, do something for the first time."],

  /* ===== CRIMEN Y DERECHO ===== */
  accomplice: ["The getaway driver was charged as an accomplice to the robbery.", "accomplice IN a crime / TO a crime."],
  acquit: ["The jury acquitted him of all charges.", "acquit sb OF sth. Contrario: convict."],
  allegation: ["The minister denied all the allegations.", "allegation OF sth / allegation THAT."],
  arson: ["The fire investigators concluded that arson was the cause.", "arsonist = persona que lo comete."],
  bail: ["He was released on bail pending trial.", "on bail = en libertad bajo fianza."],
  bribery: ["He was found guilty of bribery and corruption.", "bribe (verb/noun), bribery (noun)."],
  burglary: ["The house had been broken into: it was a professional burglary.", "burglar = ladrón de casas."],
  clemency: ["The prisoner appealed to the governor for clemency.", "show clemency = be lenient/merciful. Not a synonym of 'pardon' (indulto), which is a formal legal act."],
  collusion: ["There were clear signs of collusion between the two companies.", "in collusion WITH."],
  conviction: ["His conviction was later overturned on appeal.", "También: deep conviction = firme creencia."],
  culpable: ["The report concluded that both parties were culpable.", "culpable NEGLIGENCE = negligencia culpable."],
  deterrent: ["The threat of heavy fines acts as a strong deterrent.", "act as a deterrent TO crime."],
  embezzlement: ["He was charged with the embezzlement of pension funds.", "embezzle (verb)."],
  extortion: ["She was blackmailed and forced to pay extortion money.", "extort (verb)."],
  fraud: ["The bank discovered a sophisticated fraud involving fake accounts."],
  grievance: ["The union tabled a list of grievances to be addressed.", "lodge / air a grievance."],
  indict: ["He was indicted on three counts of tax evasion.", "indict sb FOR / ON charges."],
  incarceration: ["He faced five years of incarceration.", "incarcerate (verb)."],
  jurisdiction: ["The crime falls outside our jurisdiction.", "within / outside the jurisdiction OF."],
  larceny: ["He was convicted of petty larceny.", "Grand larceny / petty larceny."],
  manslaughter: ["She pleaded guilty to manslaughter rather than murder.", "Involuntary manslaughter = without intent."],
  misconduct: ["The doctor was struck off following findings of serious professional misconduct."],
  perpetrator: ["The perpetrators were never brought to justice.", "perpetrate (verb)."],
  prosecution: ["The prosecution presented overwhelming evidence.", "prosecution (acusación), defense (defensa)."],
  sentence: ["He was given a ten-year prison sentence.", "sentence sb TO sth."],
  smuggling: ["Customs officers seized a large smuggling operation.", "smuggle (verb), smuggler."],
  testimony: ["Her testimony was crucial to the outcome of the trial.", "give testimony / testimony OF."],
  vandalism: ["Acts of vandalism damaged several historic monuments.", "vandal, vandalise."],
  verdict: ["The jury returned a verdict of not guilty.", "reach / return a verdict."],

  /* ===== CIENCIA Y TECNOLOGÍA ===== */
  algorithm: ["The search engine uses a complex algorithm to rank results.", "algorithmic (adj)."],
  autonomous: ["Autonomous vehicles could reduce road accidents significantly.", "autonomy (noun)."],
  breakthrough: ["The discovery represents a major breakthrough in cancer research.", "make / achieve a breakthrough."],
  calibrate: ["The instruments must be carefully calibrated before use.", "calibration (noun)."],
  catalyst: ["The report acted as a catalyst for sweeping reform.", "catalyst FOR change."],
  cognition: ["The study explores the role of emotion in human cognition.", "cognitive (adj)."],
  corroborate: ["The DNA evidence corroborated the witness's account.", "corroborating evidence."],
  empirical: ["The theory is supported by a wealth of empirical data.", "empirically (adv)."],
  hypothesis: ["The hypothesis was tested under strict laboratory conditions.", "plural: hypotheses."],
  innate: ["Language acquisition appears to be an innate human capacity.", "innately (adv)."],
  iterate: ["The team iterated through dozens of prototypes before settling on a design.", "iteration (noun)."],
  paradigm: ["The discovery represented a paradigm shift in the field.", "paradigm shift = radical change of thinking."],
  peer: ["The paper was subjected to rigorous peer review before publication.", "peer-reviewed journal."],
  prototype: ["They built a working prototype within six months.", "prototype (verb) = build a first model."],
  replication: ["Replication of the original results proved impossible.", "replicate (verb)."],
  synthesis: ["The essay provides a synthesis of current research in the field.", "synthesise (verb)."],

  /* ===== LITERATURA Y ARTE ===== */
  allegory: ["The novel can be read as an allegory for political oppression.", "allegorical (adj)."],
  ambivalent: ["Critics were ambivalent about the film's rather bleak ending.", "ambivalence (noun)."],
  anachronistic: ["The playwright's modern references felt slightly anachronistic.", "anachronism (noun)."],
  cathartic: ["Many people find tragedy cathartic rather than distressing.", "catharsis (noun)."],
  cynical: ["His later work has a deeply cynical view of human nature.", "cynicism (noun)."],
  depict: ["The painting depicts a scene from classical mythology.", "depiction (noun)."],
  dystopian: ["The novel presents a chilling dystopian vision of the future.", "dystopia (noun)."],
  enigmatic: ["The poem's ending remains enigmatic, inviting multiple interpretations.", "enigma (noun)."],
  evocative: ["The film's soundtrack is powerfully evocative of the 1950s.", "evoke (verb)."],
  harrowing: ["The harrowing final chapter left readers deeply shaken.", "harrowing = deeply distressing."],
  idyllic: ["The opening chapter paints an idyllic picture of rural life.", "idyll (noun)."],
  juxtapose: ["The exhibition juxtaposes photographs from different eras.", "juxtaposition (noun)."],
  melancholic: ["The final movement of the symphony has a deeply melancholic quality.", "melancholy (noun)."],
  motif: ["The image of the sea serves as a central motif throughout the novel.", "leitmotif = recurring theme."],
  nuanced: ["Her portrayal of the character is subtle and nuanced.", "nuance (noun)."],
  paradoxical: ["It is paradoxical that increased choice can lead to greater dissatisfaction.", "paradox (noun)."],
  poignant: ["The final scene is both funny and deeply poignant.", "poignancy (noun)."],
  satirical: ["The book is a satirical attack on the media and its obsession with celebrity.", "satire (noun)."],
  seminal: ["This is a seminal text in the field of critical theory.", "seminal = highly influential and original."],
  subversive: ["Her poetry was considered subversive by the authorities.", "subversion (noun)."],
  symbolism: ["The use of water as symbolism is pervasive throughout the text.", "symbol, symbolic (adj)."],
  witty: ["The script is consistently witty without being cruel.", "wit (noun)."],

  /* ===== VERBOS FORMALES ===== */
  contend: ["Some economists contend that the policy will backfire.", "contend THAT = sostener que."],
  assert: ["The report asserts that the figures have been independently verified.", "assertion (noun)."],
  demonstrate: ["The experiment demonstrates conclusively that the compound is stable.", "demonstration (noun)."],
  facilitate: ["The new platform facilitates collaboration between remote teams.", "facilitation (noun)."],
  trigger: ["The announcement triggered a sharp drop in share prices.", "trigger (also noun) = something that sets off a reaction."],
  prompt: ["The new findings prompted an immediate review of the safety procedures.", "prompt (also adj = immediate, also noun = reminder)."],
  ameliorate: ["Several measures were adopted to ameliorate the conditions.", "amelioration (noun). More formal than 'improve'."],
  necessitate: ["The scale of the project necessitates careful planning at every stage.", "necessitate = make necessary."],
  endeavour: ["The foundation endeavours to promote access to education worldwide.", "endeavour (also noun). British spelling; US: endeavor."],
  utilise: ["The team utilised every available resource.", "utilise (British) / utilize (American). More formal than 'use'."],
  scrutinise: ["All contracts must be carefully scrutinised before signing.", "scrutiny (noun). British spelling; US: scrutinize."],
  formulate: ["They spent weeks formulating a coherent response to the crisis.", "formulation (noun)."],

  /* ===== SOCIEDAD Y MEDIOS ===== */
  accountability: ["There must be greater accountability in public life.", "accountable FOR sth."],
  advocacy: ["She dedicated her career to advocacy for refugee rights.", "advocate (verb/noun)."],
  backlash: ["The decision provoked a fierce backlash from consumer groups.", "a backlash AGAINST sth."],
  censorship: ["The film was subject to censorship before its release.", "censor (verb/noun)."],
  cohesion: ["Social cohesion is threatened by growing inequality.", "cohesive (adj)."],
  complacency: ["The report warned against any complacency about inflation.", "complacent ABOUT sth."],
  consensus: ["There is broad consensus that reform is needed.", "reach / build a consensus ON sth."],
  corruption: ["Anti-corruption measures are being strengthened.", "corrupt (adj/verb)."],
  dissent: ["The bill was passed despite significant dissent.", "dissenter (noun), dissenting voice."],
  grassroots: ["The campaign was driven by grassroots activists.", "grassroots movement = popular, bottom-up."],
  lobbyist: ["Lobbyists from the pharmaceutical industry met with the minister.", "lobby (verb/noun)."],
  monopoly: ["The company holds a near-monopoly in this sector.", "monopolise (verb)."],
  rhetoric: ["The politician's rhetoric was more convincing than her policy.", "rhetorical (adj), rhetorically."],
  sovereignty: ["The issue of national sovereignty is central to the debate.", "sovereign (adj/noun)."],
  transparency: ["Voters are demanding greater transparency in political funding.", "transparent (adj)."],

  /* ===== VOCABULARIO DE NEGACIÓN ===== */
  "by no means": ["This is by no means a comprehensive account of all the evidence.", "Seguido de inversión al inicio de frase: By no means IS this..."],
  "in no way": ["This finding is in no way conclusive.", "in no way = de ninguna manera."],
  "on no account": ["On no account should the details be shared before publication.", "Inversión obligatoria: On no account SHOULD..."],
  "under no circumstances": ["Under no circumstances are visitors permitted in the laboratory.", "Inversión obligatoria al inicio de frase."],
  "at no point": ["At no point during the investigation were these facts disclosed.", "Inversión: At no point DID they disclose..."],
  "to no avail": ["She called for help repeatedly, but to no avail.", "= without success."],
  "let alone": ["The office lacks basic supplies, let alone modern equipment.", "= and even less, much less."],
  "nothing short of": ["The speed of the response was nothing short of remarkable.", "= truly, genuinely (emphatic)."],
  "anything but": ["The transition was anything but smooth.", "= the opposite of, not at all."],
  "far from": ["The results were far from satisfactory.", "far from + adj/noun = not at all."],

  /* ===== EXPRESIONES DE GRADO Y CANTIDAD ===== */
  "a great deal of": ["A great deal of research still needs to be done.", "= a large amount of (with uncountable nouns)."],
  "a wide range of": ["The report covers a wide range of topics.", "= many different types."],
  "a host of": ["The policy has attracted a host of critics.", "= a large number of."],
  "a handful of": ["Only a handful of participants completed the full study.", "= a small number, very few."],
  "the vast majority of": ["The vast majority of respondents supported the change.", "= nearly all."],
  "to a great extent": ["The crisis was, to a great extent, caused by regulatory failure.", "= largely, in large measure."],
  "to some extent": ["To some extent, the criticism is fair.", "= partly, in some ways."],
  "by far": ["This is by far the most compelling argument in the paper.", "= by a large margin."],
  "overwhelmingly": ["The proposal was overwhelmingly rejected by the committee.", "= by a very large majority."],
  "disproportionately": ["The cuts fell disproportionately on lower-income households.", "= in a way that is too large or too small compared to what is fair."],
  "exponentially": ["The cost of the project grew exponentially.", "= at an increasingly rapid rate."],
  "marginally": ["The second candidate scored only marginally better than the first.", "= very slightly."],
  "precious few": ["There are precious few examples of this approach succeeding.", "= very few indeed (emphatic)."],
};
