export const ITEMS = [
  /* ============ OPEN CLOZE — gramática, expresiones fijas, preposiciones ============ */
  { id: "o1", type: "open", text: "The proposal was rejected on the ___ that it lacked adequate funding.", answers: ["grounds"], note: "on the grounds that = alegando que. Expresión fija." },
  { id: "o2", type: "open", text: "Little ___ he know that his findings would be challenged within a month.", answers: ["did"], note: "Inversión obligatoria tras el adverbio negativo Little." },
  { id: "o3", type: "open", text: "By no ___ is this the final version of the manuscript.", answers: ["means"], note: "By no means + inversión = en absoluto." },
  { id: "o4", type: "open", text: "She takes even the harshest criticism in her ___.", answers: ["stride"], note: "to take sth in one's stride = encajarlo sin inmutarse." },
  { id: "o5", type: "open", text: "These results fly in the ___ of everything we thought we knew.", answers: ["face"], note: "to fly in the face of = contradecir frontalmente." },
  { id: "o6", type: "open", text: "For all ___ and purposes, the negotiations are over.", answers: ["intents"], note: "for all intents and purposes = a todos los efectos." },
  { id: "o7", type: "open", text: "___ from a handful of typos, the paper is impeccable.", answers: ["apart", "aside"], note: "Apart/Aside from = salvo por." },
  { id: "o8", type: "open", text: "It is a decision she would come to ___ regret.", answers: ["bitterly", "deeply"], note: "bitterly regret: el adverbio es casi obligatorio con regret." },
  { id: "o9", type: "open", text: "Under no ___ should the data be shared before publication.", answers: ["circumstances"], note: "Under no circumstances + inversión." },
  { id: "o10", type: "open", text: "The theory has fallen ___ of favour in recent years.", answers: ["out"], note: "to fall out of favour = caer en desuso." },
  { id: "o11", type: "open", text: "No ___ is the field regarded as marginal.", answers: ["longer"], note: "No longer al inicio exige inversión del auxiliar." },
  { id: "o12", type: "open", text: "The delay was ___ no fault of her own.", answers: ["through"], note: "through no fault of one's own = sin culpa suya." },
  { id: "o13", type: "open", text: "His argument borders ___ the absurd.", answers: ["on"], note: "to border on sth = rayar en. Preposición dependiente." },
  { id: "o14", type: "open", text: "The two datasets are at odds ___ each other.", answers: ["with"], note: "at odds with = en contradicción con." },
  { id: "o15", type: "open", text: "Regardless ___ the outcome, the study was worth doing.", answers: ["of"], note: "regardless of. Nunca «regardless to»." },
  { id: "o16", type: "open", text: "The collapse resulted ___ years of underinvestment.", answers: ["from"], note: "result FROM = ser consecuencia de; result IN = causar." },
  { id: "o17", type: "open", text: "Poor design gave ___ to a whole series of errors.", answers: ["rise"], note: "to give rise to = dar lugar a." },
  { id: "o18", type: "open", text: "It goes ___ saying that every source must be cited.", answers: ["without"], note: "it goes without saying = ni que decir tiene." },
  { id: "o19", type: "open", text: "Were it ___ for the grant, the lab would have closed.", answers: ["not"], note: "Were it not for = si no fuera por. Condicional invertido." },
  { id: "o20", type: "open", text: "Hardly ___ she begun her talk when the projector failed.", answers: ["had"], note: "Hardly had + participio + when. Inversión." },
  { id: "o21", type: "open", text: "The committee was ___ two minds about the proposal.", answers: ["in"], note: "to be in two minds = estar indeciso." },
  { id: "o22", type: "open", text: "Those figures should be taken ___ a pinch of salt.", answers: ["with"], note: "to take sth with a pinch of salt." },
  { id: "o23", type: "open", text: "He is prone ___ overstating his conclusions.", answers: ["to"], note: "prone TO + -ing. Preposición dependiente del adjetivo." },
  { id: "o24", type: "open", text: "Not ___ did he refuse to apologise, but he also doubled down.", answers: ["only"], note: "Not only + inversión ... but also." },
  { id: "o25", type: "open", text: "In the ___ of further evidence, the claim is untenable.", answers: ["absence"], note: "in the absence of = a falta de." },
  { id: "o26", type: "open", text: "The blame lies ___ with the management.", answers: ["squarely"], note: "the blame lies squarely with = la culpa es de lleno de." },
  { id: "o27", type: "open", text: "___ as I admire her work, I cannot accept this conclusion.", answers: ["much"], note: "Much as + presente = por mucho que. Concesiva formal." },
  { id: "o28", type: "open", text: "His objection was neither here ___ there.", answers: ["nor"], note: "neither here nor there = irrelevante." },
  { id: "o29", type: "open", text: "She was taken ___ by the sheer hostility of the reviewers.", answers: ["aback"], note: "to be taken aback = quedarse de piedra." },
  { id: "o30", type: "open", text: "By virtue ___ her seniority, she chairs the panel.", answers: ["of"], note: "by virtue of = en virtud de." },
  { id: "o31", type: "open", text: "The evidence is open ___ more than one interpretation.", answers: ["to"], note: "open to interpretation. Preposición dependiente." },
  { id: "o32", type: "open", text: "She stopped ___ of accusing him outright.", answers: ["short"], note: "to stop short of = quedarse a un paso de." },
  { id: "o33", type: "open", text: "The project ground to a ___ when the funding dried up.", answers: ["halt", "standstill"], note: "to grind to a halt/standstill = paralizarse." },
  { id: "o34", type: "open", text: "Rarely ___ a study overturned so much received wisdom.", answers: ["has"], note: "Rarely al inicio exige inversión: Rarely has..." },
  { id: "o35", type: "open", text: "The findings are consistent ___ earlier work in the field.", answers: ["with"], note: "consistent WITH. Nunca «consistent to»." },

  /* ============ WORD FORMATION ============ */
  { id: "w1", type: "word", given: "SUSTAIN", text: "Critics question the long-term ___ of the funding model.", answers: ["sustainability"], note: "sustain → sustainable → sustainability." },
  { id: "w2", type: "word", given: "LIKELY", text: "In all ___, the deadline will be extended again.", answers: ["likelihood"], note: "in all likelihood = con toda probabilidad." },
  { id: "w3", type: "word", given: "CONCEIVE", text: "The scale of the error is almost ___ vast.", answers: ["inconceivably"], note: "conceive → inconceivable → inconceivably." },
  { id: "w4", type: "word", given: "ADVERT", text: "He ___ deleted the only copy of the file.", answers: ["inadvertently"], note: "advert → inadvertent → inadvertently = sin querer." },
  { id: "w5", type: "word", given: "STRONG", text: "Their case was considerably ___ by the new evidence.", answers: ["strengthened"], note: "strong → strengthen → strengthened." },
  { id: "w6", type: "word", given: "WEIGH", text: "Her testimony carried considerable ___ with the committee.", answers: ["weight"], note: "to carry weight = tener peso o influencia." },
  { id: "w7", type: "word", given: "KNOW", text: "She is remarkably ___ about nineteenth-century printing.", answers: ["knowledgeable"], note: "know → knowledge → knowledgeable." },
  { id: "w8", type: "word", given: "RELY", text: "The ___ of the instrument has never been established.", answers: ["reliability"], note: "rely → reliable → reliability." },
  { id: "w9", type: "word", given: "COMPARE", text: "The two samples are not directly ___.", answers: ["comparable"], note: "compare → comparable = equiparable." },
  { id: "w10", type: "word", given: "FORESEE", text: "The trial was halted due to ___ complications.", answers: ["unforeseen"], note: "foresee → foreseen → unforeseen." },
  { id: "w11", type: "word", given: "CREDIT", text: "Frankly, the explanation is simply not ___.", answers: ["credible"], note: "credit → credible = creíble." },
  { id: "w12", type: "word", given: "QUESTION", text: "The methodology is ___ sound, whatever its critics say.", answers: ["unquestionably"], note: "question → questionable → unquestionably." },
  { id: "w13", type: "word", given: "PROVE", text: "Twenty years on, the hypothesis remains ___.", answers: ["unproven"], note: "prove → proven → unproven." },
  { id: "w14", type: "word", given: "COURAGE", text: "The preliminary results are genuinely ___.", answers: ["encouraging"], note: "courage → encourage → encouraging." },
  { id: "w15", type: "word", given: "CAPABLE", text: "The system's ___ has been consistently overstated.", answers: ["capability"], note: "capable → capability." },
  { id: "w16", type: "word", given: "LEAD", text: "Under her ___, the department doubled in size.", answers: ["leadership"], note: "lead → leader → leadership." },
  { id: "w17", type: "word", given: "PERSUADE", text: "It is an elegant but ultimately un___ argument.", answers: ["persuasive", "unpersuasive"], note: "persuade → persuasive. Con el prefijo dado: unpersuasive." },
  { id: "w18", type: "word", given: "EXCEPT", text: "The response rate was ___ high for a postal survey.", answers: ["exceptionally"], note: "except → exception → exceptionally." },
  { id: "w19", type: "word", given: "RESOLVE", text: "The contradiction between the two studies remains ___.", answers: ["unresolved"], note: "resolve → resolved → unresolved." },
  { id: "w20", type: "word", given: "ASSUME", text: "The whole model rests on one shaky ___.", answers: ["assumption"], note: "assume → assumption." },
  { id: "w21", type: "word", given: "TENABLE", text: "After the retraction, his position became ___.", answers: ["untenable"], note: "tenable → untenable = insostenible." },
  { id: "w22", type: "word", given: "DEEP", text: "The latest data only ___ the mystery.", answers: ["deepens", "deepen"], note: "deep → deepen. Tercera persona: deepens." },
  { id: "w23", type: "word", given: "FAIL", text: "His ___ to disclose the conflict of interest was fatal.", answers: ["failure"], note: "fail → failure + to + infinitivo." },
  { id: "w24", type: "word", given: "SUBSTANCE", text: "There is ___ evidence for the opposite view.", answers: ["substantial"], note: "substance → substantial = considerable." },

  /* ============ KEY WORD TRANSFORMATION ============ */
  { id: "t1", type: "trans", lead: "I regret not applying for the grant last year.", given: "WISH", text: "I ___ for the grant last year.", answers: ["wish i had applied"], note: "wish + past perfect para lamentar el pasado." },
  { id: "t2", type: "trans", lead: "Nobody expected him to resign so abruptly.", given: "TOOK", text: "His abrupt resignation ___ surprise.", answers: ["took everyone by"], note: "to take sb by surprise." },
  { id: "t3", type: "trans", lead: "As soon as she arrived, the meeting began.", given: "SOONER", text: "No ___ than the meeting began.", answers: ["sooner had she arrived"], note: "No sooner had + participio + than." },
  { id: "t4", type: "trans", lead: "People say the report is biased.", given: "SAID", text: "The report ___ biased.", answers: ["is said to be"], note: "Pasiva impersonal: is said to be." },
  { id: "t5", type: "trans", lead: "It was only later that I understood the implications.", given: "DAWN", text: "The implications ___ me until later.", answers: ["did not dawn on", "didn't dawn on"], note: "to dawn on sb = caer en la cuenta." },
  { id: "t6", type: "trans", lead: "It doesn't matter how hard you try; you can't please everyone.", given: "MATTER", text: "___ you try, you can't please everyone.", answers: ["no matter how hard"], note: "No matter how + adjetivo/adverbio." },
  { id: "t7", type: "trans", lead: "I only realised the mistake afterwards.", given: "UNTIL", text: "It ___ afterwards that I realised the mistake.", answers: ["was not until", "wasn't until"], note: "Estructura enfática: It was not until X that Y." },
  { id: "t8", type: "trans", lead: "She rarely admits that she is wrong.", given: "SELDOM", text: "___ she admit that she is wrong.", answers: ["seldom does"], note: "Seldom al inicio exige inversión con do/does." },
  { id: "t9", type: "trans", lead: "They had to cancel the conference because of the strike.", given: "RESULT", text: "The conference had to be cancelled ___ the strike.", answers: ["as a result of"], note: "as a result of = a consecuencia de." },
  { id: "t10", type: "trans", lead: "He didn't mention the funding problem at all.", given: "MENTION", text: "He ___ the funding problem.", answers: ["made no mention of"], note: "to make no mention of sth." },
  { id: "t11", type: "trans", lead: "Everyone was very surprised when she resigned.", given: "MUCH", text: "___ surprise, she resigned.", answers: ["much to everyone's"], note: "Much to sb's surprise = para gran sorpresa de." },
  { id: "t12", type: "trans", lead: "I'd prefer you not to tell anyone about this.", given: "KEEP", text: "I'd rather you ___ yourself.", answers: ["kept it to"], note: "would rather + pasado; to keep sth to oneself." },
  { id: "t13", type: "trans", lead: "The two accounts are completely different.", given: "RESEMBLANCE", text: "The two accounts ___ each other.", answers: ["bear no resemblance to"], note: "to bear no resemblance to = no parecerse en nada a." },
  { id: "t14", type: "trans", lead: "She was determined not to give in.", given: "INTENTION", text: "She ___ giving in.", answers: ["had no intention of"], note: "to have no intention of + -ing." },
  { id: "t15", type: "trans", lead: "Nobody has ever explained this properly.", given: "BEEN", text: "This ___ explained.", answers: ["has never been properly"], note: "Pasiva en present perfect con adverbio intercalado." },
  { id: "t16", type: "trans", lead: "There's no use complaining at this stage.", given: "POINT", text: "There ___ complaining at this stage.", answers: ["is no point in", "'s no point in"], note: "there is no point in + -ing." },
  { id: "t17", type: "trans", lead: "The results surprised even the authors.", given: "CAME", text: "The results ___ even to the authors.", answers: ["came as a surprise"], note: "to come as a surprise to sb." },
  { id: "t18", type: "trans", lead: "She is very likely to be promoted soon.", given: "CHANCES", text: "The ___ she will be promoted soon.", answers: ["chances are that", "chances are"], note: "the chances are (that) = lo más probable es que." },

  /* ============ GAPPED SENTENCES — una palabra para tres frases ============ */
  { id: "g1", type: "gapped", sentences: ["She finally agreed to ___ for office.", "The exhibition will ___ until September.", "Let me ___ those figures past you again."], answers: ["run"], note: "run for office / a show runs / run sth past sb." },
  { id: "g2", type: "gapped", sentences: ["There is no ___ in arguing about it now.", "He made one genuinely valid ___.", "At one ___ I very nearly gave up."], answers: ["point"], note: "no point in / make a point / at one point." },
  { id: "g3", type: "gapped", sentences: ["The match ended in a goalless ___.", "The lecture is bound to ___ a large crowd.", "Readers must ___ their own conclusions."], answers: ["draw"], note: "a draw / draw a crowd / draw conclusions." },
  { id: "g4", type: "gapped", sentences: ["I can't ___ the noise from the street.", "His argument doesn't ___ close scrutiny.", "___ in mind that funds are limited."], answers: ["bear"], note: "bear the noise / bear scrutiny / bear in mind." },
  { id: "g5", type: "gapped", sentences: ["Those old assumptions no longer ___.", "Could you ___ the line for a moment?", "She has a firm ___ on the subject."], answers: ["hold"], note: "an assumption holds / hold the line / a hold on sth." },
  { id: "g6", type: "gapped", sentences: ["Enrolment began to ___ sharply after 2010.", "The blame will ___ on the committee.", "Don't ___ for that old trick."], answers: ["fall"], note: "fall sharply / fall on sb / fall for sth." },
  { id: "g7", type: "gapped", sentences: ["The charity hopes to ___ half a million.", "This is bound to ___ awkward questions.", "She asked her boss for a ___."], answers: ["raise"], note: "raise funds / raise questions / a pay raise." },
  { id: "g8", type: "gapped", sentences: ["That is simply not the ___ here.", "She presented a compelling ___ for reform.", "In any ___, a decision must be made."], answers: ["case"], note: "that's not the case / make a case / in any case." },
  { id: "g9", type: "gapped", sentences: ["The seminar covered a lot of ___.", "He stood his ___ under fierce questioning.", "Their last paper broke new ___."], answers: ["ground"], note: "cover ground / stand one's ground / break new ground." },
  { id: "g10", type: "gapped", sentences: ["Fresh evidence has come to ___.", "She made ___ of a very serious problem.", "The archive room needs far more ___."], answers: ["light"], note: "come to light / make light of / natural light." },

  /* ============ MULTIPLE-CHOICE CLOZE ============ */
  { id: "m1", type: "mcq", text: "The article ___ heavily on unpublished archival sources.", options: ["draws", "makes", "takes", "gives"], answers: ["draws"], note: "to draw on sth = basarse en una fuente.", whyNot: { makes: "«make on» no existe como verbo con preposición.", takes: "«take on» significa asumir o enfrentarse a algo, no apoyarse en ello.", gives: "«give on» solo se usa para ventanas que dan a un sitio." } },
  { id: "m2", type: "mcq", text: "There is a ___ contrast between the two approaches.", options: ["stark", "sheer", "blunt", "raw"], answers: ["stark"], note: "stark contrast: colocación fija.", whyNot: { sheer: "«sheer» acompaña a tamaño o cantidad: sheer scale, sheer number.", blunt: "«blunt» va con instrument o refusal, no con contrast.", raw: "«raw» va con emotion o data, y aporta la idea de «en bruto»." } },
  { id: "m3", type: "mcq", text: "Junior staff ___ the brunt of the restructuring.", options: ["bore", "carried", "held", "brought"], answers: ["bore"], note: "to bear the brunt of sth.", whyNot: { carried: "«brunt» solo colocaciona con bear, por muy lógico que suene carry.", held: "«hold» no se combina nunca con brunt.", brought: "«bring» cambiaría el sentido: traer, no soportar." } },
  { id: "m4", type: "mcq", text: "That is a rather ___ generalisation about an entire field.", options: ["sweeping", "wide", "large", "roomy"], answers: ["sweeping"], note: "a sweeping generalisation.", whyNot: { wide: "«wide» no colocaciona con generalisation; sí con range o gap.", large: "«large» mide tamaño físico o cantidad, no alcance argumental.", roomy: "«roomy» describe espacios amplios: una habitación o un coche." } },
  { id: "m5", type: "mcq", text: "___ to popular belief, the effect is remarkably small.", options: ["Contrary", "Opposite", "Reverse", "Converse"], answers: ["contrary"], note: "contrary to popular belief: fórmula fija.", whyNot: { Opposite: "«opposite» es posición física: the opposite side.", Reverse: "«reverse» es sustantivo o verbo, no lleva «to» así.", Converse: "«the converse» existe, pero no forma «converse to belief»." } },
  { id: "m6", type: "mcq", text: "Two independent witnesses ___ to the accuracy of the report.", options: ["attested", "confirmed", "proved", "assured"], answers: ["attested"], note: "attest TO sth. La clave es la preposición dependiente.", whyNot: { confirmed: "«confirm» es transitivo directo: confirm the accuracy, sin «to».", proved: "«prove» tampoco lleva «to» con este sentido.", assured: "«assure» necesita persona como objeto: assure sb of sth." } },
  { id: "m7", type: "mcq", text: "He was completely ___ with grief after the news.", options: ["overcome", "overtaken", "overrun", "overturned"], answers: ["overcome"], note: "to be overcome with grief/emotion.", whyNot: { overtaken: "«overtake» es adelantar o sobrevenir de golpe: overtaken BY events.", overrun: "«overrun» es invadir o excederse en tiempo.", overturned: "«overturn» es revocar una decisión o volcar algo." } },
  { id: "m8", type: "mcq", text: "The whole affair was ___ in secrecy from the outset.", options: ["shrouded", "covered", "hidden", "masked"], answers: ["shrouded"], note: "shrouded in secrecy/mystery: colocación fija.", whyNot: { covered: "«covered in» va con sustancias: covered in dust.", hidden: "«hidden» no admite «in secrecy» como complemento.", masked: "«mask» oculta algo concreto, no forma esta expresión." } },
  { id: "m9", type: "mcq", text: "The rumour ___ like wildfire through the department.", options: ["spread", "ran", "flew", "passed"], answers: ["spread"], note: "to spread like wildfire = correr como la pólvora.", whyNot: { ran: "«run» no forma parte del símil fijo con wildfire.", flew: "«fly» sugiere velocidad pero rompe la expresión hecha.", passed: "«pass» implica transmisión ordenada, no propagación." } },
  { id: "m10", type: "mcq", text: "The reviewers ___ serious doubt on his methodology.", options: ["cast", "threw", "put", "laid"], answers: ["cast"], note: "to cast doubt on sth = poner en duda.", whyNot: { threw: "«throw doubt» aparece a veces, pero la forma estándar es cast.", put: "«put doubt on» no es una colocación aceptada.", laid: "«lay» va con blame o foundations, no con doubt." } },
  { id: "m11", type: "mcq", text: "The pilot scheme ___ well short of expectations.", options: ["fell", "came", "went", "dropped"], answers: ["fell"], note: "to fall short of = no llegar a, quedarse corto.", whyNot: { came: "«come short of» no se usa en inglés moderno.", went: "«go short of» significa carecer de algo, otro sentido.", dropped: "«drop short» pertenece al deporte, no a este registro." } },
  { id: "m12", type: "mcq", text: "She ___ the blame for a failure that was not hers.", options: ["shouldered", "lifted", "wore", "gripped"], answers: ["shouldered"], note: "to shoulder the blame/responsibility.", whyNot: { lifted: "«lift» sería quitar la culpa, no asumirla.", wore: "«wear the blame» es coloquialismo australiano, no estándar.", gripped: "«grip» es agarrar físicamente." } },
];
