/* Vocabulario C1–C2 (material DET). Origen: guía de estudio del usuario. */

export const VOCAB = [
  {
    id: "academicas",
    title: "Académicas frecuentes",
    note: "Deberías tenerlas automatizadas.",
    kind: "pairs",
    items: [
      ["consultation", "consulta, asesoramiento"],
      ["conclusively", "de forma concluyente"],
      ["disruptive", "disruptivo, perturbador"],
      ["intolerable", "intolerable"],
      ["immune", "inmune"],
      ["reckless", "imprudente, temerario"],
      ["offspring", "descendencia, prole"],
      ["strive", "esforzarse, luchar por"],
      ["thereafter", "a partir de entonces"],
      ["scramble", "apresurarse / revolver"],
      ["underway", "en marcha, en curso"],
      ["strategically", "estratégicamente"],
      ["scattered", "disperso, esparcido"],
      ["remorse", "remordimiento"],
      ["complimentary", "gratuito / elogioso"],
      ["additive", "aditivo"],
      ["burial", "entierro"],
      ["blunt", "romo / directo, sin rodeos"],
      ["totalitarian", "totalitario"],
    ],
  },
  {
    id: "registro-alto",
    title: "Registro alto",
    note: "Aquí se juega el C1.",
    kind: "pairs",
    items: [
      ["heinous", "atroz, execrable"],
      ["pensive", "pensativo, meditabundo"],
      ["pristine", "inmaculado, prístino"],
      ["zealous", "ferviente, celoso"],
      ["quaint", "pintoresco, con encanto anticuado"],
      ["eloquent", "elocuente"],
      ["swarthy", "moreno, atezado"],
      ["lozenge", "pastilla (para la garganta) / rombo"],
      ["alabaster", "alabastro"],
      ["obfuscate", "ofuscar, enturbiar deliberadamente"],
      ["prevaricate", "andarse con evasivas (ojo: NO es «prevaricar»)"],
      ["burble", "borbotear / parlotear"],
      ["fustigate", "fustigar, criticar duramente"],
    ],
  },
  {
    id: "ampliacion",
    title: "Ampliación de registro",
    note: "Mismo nivel que el bloque anterior. Si dominas esto, el algoritmo adaptativo deja de poder subirte.",
    kind: "pairs",
    items: [
      ["ubiquitous", "omnipresente"], ["tenuous", "endeble, tenue"],
      ["meticulous", "meticuloso"], ["opaque", "opaco"],
      ["candid", "franco, sincero"], ["plausible", "verosímil"],
      ["cogent", "convincente, sólido"], ["tacit", "tácito"],
      ["astute", "astuto, perspicaz"], ["innocuous", "inocuo"],
      ["arduous", "arduo"], ["redundant", "superfluo, redundante"],
      ["lucid", "lúcido, claro"], ["volatile", "volátil, inestable"],
      ["succinct", "sucinto"], ["prudent", "prudente"],
      ["resilient", "resiliente"], ["inherent", "inherente"],
      ["ambiguous", "ambiguo"], ["coherent", "coherente"],
      ["feasible", "factible"], ["scarce", "escaso"],
      ["stagnant", "estancado"], ["vigilant", "vigilante"],
      ["profound", "profundo"], ["inevitable", "inevitable"],
      ["sporadic", "esporádico"], ["rigorous", "riguroso"],
      ["detrimental", "perjudicial"], ["pervasive", "penetrante, extendido"],
      ["compelling", "convincente, absorbente"], ["mundane", "mundano, anodino"],
      ["austere", "austero"], ["florid", "recargado, florido"],
      ["brazen", "descarado"], ["languid", "lánguido"],
      ["taciturn", "taciturno"], ["garrulous", "locuaz, parlanchín"],
      ["obstinate", "obstinado"], ["amenable", "receptivo, dispuesto"],
      ["ephemeral", "efímero"], ["intrepid", "intrépido"],
      ["soporific", "soporífero"], ["truculent", "agresivo, belicoso"],
      ["perfunctory", "superficial, rutinario"], ["trenchant", "incisivo, mordaz"],
      ["assiduous", "asiduo, aplicado"], ["inscrutable", "inescrutable"],
      ["ostensible", "aparente, supuesto"], ["recalcitrant", "recalcitrante"],
    ],
  },
  {
    id: "falsos-amigos",
    title: "Falsos amigos",
    note: "Trampas clásicas para hispanohablantes.",
    kind: "pairs",
    items: [
      ["prevaricate", "andarse con evasivas — no «prevaricar»"],
      ["actually", "en realidad — no «actualmente»"],
      ["eventually", "finalmente — no «eventualmente»"],
      ["sensible", "sensato — no «sensible»"],
      ["sympathetic", "comprensivo — no «simpático»"],
      ["argument", "discusión (también argumento)"],
      ["advertisement", "anuncio"],
      ["attend", "asistir — no «atender»"],
      ["realize", "darse cuenta"],
      ["assist", "ayudar — no «asistir a un evento»"],
      ["resume", "reanudar"],
      ["pretend", "fingir"],
      ["support", "apoyar — no «soportar»"],
      ["library", "biblioteca"],
      ["carpet", "alfombra"],
      ["fabric", "tejido"],
      ["constipated", "estreñido"],
    ],
  },
  {
    id: "prepositions",
    title: "Preposiciones dependientes",
    note: "El error nº 1 en producción escrita. Memorízalas como bloque.",
    kind: "pairs",
    items: [
      ["depend", "on"], ["consist", "of"],
      ["result", "in (causar) / from (ser consecuencia de)"], ["rely", "on"],
      ["succeed", "in"], ["interested", "in"],
      ["capable", "of"], ["responsible", "for"],
      ["aware", "of"], ["accustomed", "to"],
      ["insist", "on"], ["approve", "of"],
      ["concerned", "about"], ["contribute", "to"],
      ["based", "on"], ["subject", "to"],
      ["in contrast", "to"], ["at the expense", "of"],
    ],
  },
  {
    id: "ortografia",
    title: "Ortografía británica y americana",
    note: "Ambas valen en Read and Select y en escritura. En Read and Complete, solo la americana.",
    kind: "pairs",
    items: [
      ["travelling, cancelled, modelling", "traveling, canceled, modeling"],
      ["centre, theatre, metre", "center, theater, meter"],
      ["colour, behaviour, favour", "color, behavior, favor"],
      ["organise, analyse, realise", "organize, analyze, realize"],
      ["defence, licence (n.)", "defense, license"],
      ["catalogue, dialogue", "catalog, dialog"],
      ["programme", "program"],
      ["grey", "gray"],
      ["judgement", "judgment"],
    ],
  },
  {
    id: "faltas",
    title: "Palabras que casi todos escriben mal",
    kind: "list",
    items: [
      "accommodate", "occurrence", "occurred", "necessary", "embarrass", "definitely",
      "separate", "privilege", "rhythm", "conscience", "conscientious", "maintenance",
      "recommend", "argument", "existence", "independent", "liaison", "millennium",
      "questionnaire", "restaurant", "threshold", "weird", "bureaucracy", "entrepreneur",
      "acquaintance", "indispensable", "perseverance", "supersede", "harass", "publicly",
      "foreign", "colleague", "exaggerate", "hierarchy", "noticeable", "parallel",
      "pronunciation", "referred", "relevant", "twelfth", "vacuum", "apparent",
      "committee", "curiosity", "guarantee", "immediately",
    ],
  },
  {
    id: "afijos",
    title: "Afijos y raíces",
    note: "Identifica primero la categoría gramatical que pide el hueco, y luego el tiempo verbal.",
    kind: "groups",
    groups: [
      { label: "→ sustantivo", items: ["-tion / -sion (implication, provision)", "-ment (assessment)", "-ness (awareness)", "-ity (feasibility)", "-ance / -ence (reluctance, coherence)", "-ship (relationship)", "-hood (likelihood)", "-ism (activism)", "-ure (exposure)"] },
      { label: "→ adjetivo", items: ["-ous (ambiguous)", "-ive (disruptive)", "-al (marginal)", "-able / -ible (feasible)", "-ful / -less (resourceful, relentless)", "-ic (systematic)", "-ary (arbitrary)", "-ent / -ant (persistent, significant)"] },
      { label: "→ verbo", items: ["-ize / -ise (prioritize)", "-ify (clarify)", "-ate (facilitate)", "-en (strengthen)"] },
      { label: "→ adverbio", items: ["-ly (conclusively, strategically)"] },
      { label: "prefijos frecuentes", items: ["un- / in- / im- / ir- / il- (negación)", "dis-", "mis- (mal)", "over- / under- (exceso o defecto)", "re- (de nuevo)", "pre- / post-", "sub-", "inter-", "trans-", "anti-", "co-", "counter-", "pseudo-", "hyper-"] },
    ],
  },
  {
    id: "colocaciones",
    title: "Colocaciones por tema",
    note: "Esto es lo que sube de C1 a C2 en producción.",
    kind: "groups",
    groups: [
      { label: "Tecnología e IA", items: ["a double-edged sword", "to reshape the landscape of", "algorithmic bias", "to blur the line between", "digital literacy", "a breeding ground for misinformation", "to streamline processes", "at the expense of privacy", "unprecedented access to", "to lag behind technologically", "echo chamber", "screen fatigue"] },
      { label: "Educación y aprendizaje", items: ["rote memorization", "to foster critical thinking", "a one-size-fits-all approach", "to tailor instruction to", "lifelong learning", "academic rigour", "to bridge the achievement gap", "hands-on experience", "to instil a love of learning", "a stepping stone to", "to fall through the cracks"] },
      { label: "Medio ambiente", items: ["to curb emissions", "carbon footprint", "at an alarming rate", "to deplete natural resources", "a pressing concern", "environmentally conscious", "to mitigate the impact of", "renewable alternatives", "irreversible damage", "to strike a balance between growth and conservation"] },
      { label: "Sociedad y justicia social", items: ["systemic inequality", "to marginalise communities", "a collective responsibility", "to raise awareness of", "civic engagement", "social mobility", "to bear the brunt of", "a safety net", "vested interests", "to level the playing field"] },
      { label: "Trabajo y desarrollo profesional", items: ["to hone one's skills", "job satisfaction", "a demanding workload", "to climb the career ladder", "transferable skills", "burnout", "to negotiate terms", "a rewarding career path", "to take on responsibility", "work–life balance"] },
      { label: "Cultura y viajes", items: ["to broaden one's horizons", "deeply rooted traditions", "a melting pot of cultures", "culture shock", "off the beaten track", "to immerse oneself in", "a lasting impression", "cultural exchange", "to gain a fresh perspective"] },
      { label: "Creatividad y expresión", items: ["a form of self-expression", "to spark the imagination", "artistic licence", "to convey emotion", "a creative outlet", "to push boundaries", "a source of inspiration", "to resonate with an audience"] },
      { label: "Ética y moral", items: ["a moral dilemma", "to weigh the pros and cons", "at odds with one's principles", "to draw the line at", "a grey area", "to act in good faith", "to hold oneself accountable", "conflicting interests"] },
      { label: "Salud y estilo de vida", items: ["a sedentary lifestyle", "to take a toll on", "to prioritise well-being", "mindful habits", "to build resilience", "chronic stress", "in moderation", "to unwind after a long day"] },
      { label: "Relaciones y comunidad", items: ["a sense of belonging", "to forge lasting friendships", "mutual respect", "to lend a hand", "common ground", "to keep in touch", "a tight-knit community", "to fall out with someone"] },
      { label: "Describir fotos", items: ["in the foreground / in the background", "to the left / right of", "scattered across", "strewn with", "nestled between", "surrounded by", "appears to be", "what strikes me most is", "judging by their expressions", "a bustling scene", "dimly lit", "sun-drenched", "snow-capped peaks", "a steep climb", "engrossed in"] },
    ],
  },
  {
    id: "conectores",
    title: "Conectores y frases funcionales",
    kind: "groups",
    groups: [
      { label: "Introducir", items: ["It is often argued that…", "There is little doubt that…", "At first glance, X may seem…, but…"] },
      { label: "Añadir", items: ["Moreover", "Furthermore", "What is more", "Not only… but also…", "In addition to this"] },
      { label: "Contrastar", items: ["However", "Nevertheless", "Conversely", "That said", "Whereas", "While it is true that…, it is equally important to…"] },
      { label: "Conceder y rebatir", items: ["Admittedly, … yet…", "Granted, …", "Critics may contend that…, but this overlooks…"] },
      { label: "Ejemplificar", items: ["For instance", "A case in point is", "To illustrate", "Take, for example"] },
      { label: "Causa y consecuencia", items: ["Consequently", "As a result", "This gives rise to", "Owing to", "Hence", "Therefore"] },
      { label: "Matizar la opinión", items: ["I would argue that", "It seems to me that", "To my mind", "I am inclined to think that", "There is a strong case for"] },
      { label: "Concluir", items: ["All things considered", "On balance", "Ultimately", "Taking everything into account"] },
    ],
  },
  {
    id: "estructuras",
    title: "Estructuras que suben la nota",
    kind: "groups",
    groups: [
      { label: "Relativas", items: ["…, which suggests that…", "…, whose impact is felt…"] },
      { label: "Inversión", items: ["Not only does this…, but it also…", "Rarely have I encountered…", "Only when… did I realise…"] },
      { label: "Condicionales avanzados", items: ["Had I known…, I would have…", "Were it not for…"] },
      { label: "Enfáticas", items: ["What matters most is…", "It is precisely this that…"] },
      { label: "Participiales", items: ["Having considered both sides, …", "Faced with such a choice, …"] },
      { label: "Modales de matiz", items: ["may well", "might arguably", "could conceivably", "would tend to"] },
      { label: "Perífrasis de emergencia", items: ["It's a kind of device which…", "It's something used to…"] },
    ],
  },
];
