/* Vocabulario C1–C2 ampliado. Phrasal verbs, idioms, collocations,
   preposiciones dependientes, registro alto, falsos amigos y más. */

export const VOCAB = [
  /* ================================================================
     SECCIÓN 1 — ACADÉMICAS FRECUENTES
     ================================================================ */
  {
    id: "academicas",
    title: "Académicas frecuentes",
    note: "Deberías tenerlas automatizadas.",
    kind: "pairs",
    items: [
      ["consultation", "consulta, asesoramiento"],
      ["conclusively", "de forma concluyente"],
      ["disruptive", "disruptivo, perturbador"],
      ["intolerable", "intolerable"],
      ["immune", "inmune"],
      ["reckless", "imprudente, temerario"],
      ["offspring", "descendencia, prole"],
      ["strive", "esforzarse, luchar por"],
      ["thereafter", "a partir de entonces"],
      ["scramble", "apresurarse / revolver"],
      ["underway", "en marcha, en curso"],
      ["strategically", "estratégicamente"],
      ["scattered", "disperso, esparcido"],
      ["remorse", "remordimiento"],
      ["complimentary", "gratuito / elogioso"],
      ["additive", "aditivo"],
      ["burial", "entierro"],
      ["blunt", "romo / directo, sin rodeos"],
      ["totalitarian", "totalitario"],
      ["arbitrary", "arbitrario"],
      ["complacency", "autocomplacencia, conformismo"],
      ["unprecedented", "sin precedentes"],
      ["scrutiny", "escrutinio, examen riguroso"],
      ["discrepancy", "discrepancia, desajuste"],
      ["rationale", "razón de ser, fundamento lógico"],
      ["tangible", "tangible, concreto"],
      ["discern", "discernir, distinguir"],
      ["alleviate", "aliviar, paliar"],
      ["exacerbate", "exacerbar, agravar"],
      ["mitigate", "mitigar, atenuar"],
      ["syringes", "jeringuillas"],
      ["aim", "objetivo, propósito (n.) / aspirar a (v.)"],
      ["intricacies", "entresijos, complejidades"],
      ["uninitiated", "los profanos, los no iniciados — casi siempre «to the uninitiated»"],
      ["sliding door", "puerta corredera"],
      ["ceiling", "techo (literal) / tope máximo (figurado)"],
      ["edge", "borde, filo / ventaja competitiva"],
      ["boundaries", "límites (personales, académicos, conceptuales)"],
      ["border", "frontera política o geográfica"],
      ["reliable", "fiable, de confianza"],
      ["daunting", "intimidante, abrumador"],
      ["supply", "suministro (n.) / suministrar (v.)"],
      ["arise", "surgir (intransitivo) — nunca «arise sth»"],
      ["return", "volver / devolver — el más neutro y general"],
      ["retrace", "desandar / reconstruir un camino paso a paso"],
      ["regress", "retroceder a un estado anterior peor — connotación negativa"],
    ],
  },

  /* ================================================================
     SECCIÓN 2 — REGISTRO ALTO
     ================================================================ */
  {
    id: "registro-alto",
    title: "Registro alto",
    note: "Aquí se juega el C1.",
    kind: "pairs",
    items: [
      ["heinous", "atroz, execrable"],
      ["pensive", "pensativo, meditabundo"],
      ["pristine", "inmaculado, prístino"],
      ["zealous", "ferviente, celoso"],
      ["quaint", "pintoresco, con encanto anticuado"],
      ["eloquent", "elocuente"],
      ["swarthy", "moreno, atezado"],
      ["lozenge", "pastilla (garganta) / rombo"],
      ["alabaster", "alabastro"],
      ["obfuscate", "ofuscar, enturbiar deliberadamente"],
      ["prevaricate", "andarse con evasivas (NO 'prevaricar')"],
      ["burble", "borbotear / parlotear"],
      ["fustigate", "fustigar, criticar duramente"],
      ["impetuous", "impetuoso, precipitado"],
      ["mendacious", "mendaz, embustero"],
      ["laconic", "lacónico, escueto"],
      ["fastidious", "meticuloso, quisquilloso"],
      ["sycophantic", "adulador, servil"],
      ["magnanimous", "magnánimo, generoso"],
      ["vociferous", "vociferante, ruidoso"],
      ["benevolent", "benévolo, bondadoso"],
      ["inveterate", "empedernido, incorregible"],
      ["ostentatious", "ostentoso, llamativo"],
      ["reticent", "reservado, callado"],
      ["veracious", "veraz, verídico"],
      ["inimical", "hostil, contrario a"],
      ["propitious", "propicio, favorable"],
      ["querulous", "quejumbroso, irritable"],
      ["dispassionate", "desapasionado, objetivo"],
      ["pernicious", "pernicioso, muy dañino"],
    ],
  },

  /* ================================================================
     SECCIÓN 3 — AMPLIACIÓN DE REGISTRO
     ================================================================ */
  {
    id: "ampliacion",
    title: "Ampliación de registro",
    note: "Mismo nivel que el bloque anterior. Si dominas esto, el algoritmo adaptativo deja de poder subirte.",
    kind: "pairs",
    items: [
      ["ubiquitous", "omnipresente"], ["tenuous", "endeble, tenue"],
      ["meticulous", "meticuloso"], ["opaque", "opaco"],
      ["candid", "franco, sincero"], ["plausible", "verosímil"],
      ["cogent", "convincente, sólido"], ["tacit", "tácito"],
      ["astute", "astuto, perspicaz"], ["innocuous", "inocuo"],
      ["arduous", "arduo"], ["redundant", "superfluo / despedido (brit.)"],
      ["lucid", "lúcido, claro"], ["volatile", "volátil, inestable"],
      ["succinct", "sucinto"], ["prudent", "prudente"],
      ["resilient", "resiliente"], ["inherent", "inherente"],
      ["ambiguous", "ambiguo"], ["coherent", "coherente"],
      ["feasible", "factible"], ["scarce", "escaso"],
      ["stagnant", "estancado"], ["vigilant", "vigilante"],
      ["profound", "profundo (abstracto)"], ["inevitable", "inevitable"],
      ["sporadic", "esporádico"], ["rigorous", "riguroso"],
      ["detrimental", "perjudicial"], ["pervasive", "penetrante, extendido"],
      ["compelling", "convincente, absorbente"], ["mundane", "mundano, anodino"],
      ["austere", "austero"], ["florid", "recargado, florido"],
      ["brazen", "descarado"], ["languid", "lánguido"],
      ["taciturn", "taciturno"], ["garrulous", "locuaz, parlanchín"],
      ["obstinate", "obstinado"], ["amenable", "receptivo, dispuesto"],
      ["ephemeral", "efímero"], ["intrepid", "intrépido"],
      ["soporific", "soporífero"], ["truculent", "agresivo, belicoso"],
      ["perfunctory", "superficial, rutinario"], ["trenchant", "incisivo, mordaz"],
      ["assiduous", "asiduo, aplicado"], ["inscrutable", "inescrutable"],
      ["ostensible", "aparente, supuesto"], ["recalcitrant", "recalcitrante"],
    ],
  },

  /* ================================================================
     SECCIÓN 4 — FALSOS AMIGOS
     ================================================================ */
  {
    id: "falsos-amigos",
    title: "Falsos amigos",
    note: "Trampas clásicas para hispanohablantes.",
    kind: "pairs",
    items: [
      ["prevaricate", "andarse con evasivas — no «prevaricar»"],
      ["actually", "en realidad — no «actualmente»"],
      ["eventually", "finalmente — no «eventualmente»"],
      ["sensible", "sensato — no «sensible»"],
      ["sympathetic", "comprensivo — no «simpático»"],
      ["argument", "discusión (también argumento)"],
      ["advertisement", "anuncio"],
      ["attend", "asistir — no «atender»"],
      ["realize", "darse cuenta"],
      ["assist", "ayudar — no «asistir a un evento»"],
      ["resume", "reanudar"],
      ["pretend", "fingir"],
      ["support", "apoyar — no «soportar»"],
      ["library", "biblioteca"],
      ["carpet", "alfombra"],
      ["fabric", "tejido"],
      ["constipated", "estreñido"],
      ["comprehensive", "exhaustivo — no «comprensivo»"],
      ["embarrassed", "avergonzado — no «embarazada»"],
      ["deception", "engaño — no «decepción»"],
      ["disgusted", "asqueado — no «disgustado»"],
      ["ingenious", "ingenioso — no «ingenuo»"],
      ["miserable", "desdichado — no «miserable (tacaño)»"],
      ["notorious", "de mala fama — no «notorio (conocido)»"],
      ["particular", "específico, exigente — no siempre «particular»"],
      ["proper", "adecuado, correcto — no «propio»"],
      ["rare", "raro / poco hecho (carne) — no siempre «raro»"],
      ["sensitive", "sensible (emotivo) — no «sensato»"],
      ["trivial", "insignificante — no «trivial (trillado)»"],
      ["vicinity", "inmediaciones — «in the vicinity of» también = «aproximadamente»"],
      ["succeeding", "siguiente(s), sucesivo(s) (adj.) — no confundir con succeed (v.) = tener éxito"],
    ],
  },

  /* ================================================================
     SECCIÓN 5 — PHRASAL VERBS C1/C2 — MOVIMIENTO Y ACCIÓN
     ================================================================ */
  {
    id: "phrasal-movimiento",
    title: "Phrasal verbs: movimiento y acción",
    note: "Los más frecuentes en Use of English. Apréndalos por grupos de verbo base.",
    kind: "pairs",
    items: [
      ["bring about", "provocar, causar (un cambio)"],
      ["bring forward", "adelantar (una reunión)"],
      ["bring off", "lograr algo difícil"],
      ["bring up", "mencionar / criar (a un hijo)"],
      ["call for", "exigir, requerir"],
      ["call off", "cancelar"],
      ["call up", "convocar / llamar por teléfono"],
      ["carry out", "llevar a cabo, realizar"],
      ["come across", "encontrarse con / dar la impresión de"],
      ["come about", "ocurrir, producirse"],
      ["come up with", "idear, proponer"],
      ["come to terms with", "aceptar, asumir"],
      ["die out", "extinguirse"],
      ["fall apart", "desmoronarse"],
      ["fall back on", "recurrir a (como último recurso)"],
      ["fall through", "fracasar, no llegar a realizarse"],
      ["get across", "comunicar (un mensaje) con éxito"],
      ["get around to", "encontrar tiempo para hacer algo"],
      ["get away with", "salirse con la suya"],
      ["get over", "superar, recuperarse de"],
      ["give in", "rendirse, ceder"],
      ["give rise to", "dar lugar a"],
      ["give way to", "ceder el paso a / ser reemplazado por"],
      ["go through with", "llevar a cabo (algo difícil)"],
      ["hold back", "contener / reprimir"],
      ["hold out", "resistir / ofrecer (esperanza)"],
      ["keep up with", "mantener el ritmo con"],
      ["let down", "decepcionar, fallar"],
      ["look into", "investigar"],
      ["make up for", "compensar"],
      ["phase out", "eliminar progresivamente"],
      ["pick up on", "percatarse de, captar"],
      ["pull off", "lograr algo difícil"],
      ["put across", "comunicar, transmitir"],
      ["put forward", "proponer, presentar"],
      ["put off", "aplazar / desanimar"],
      ["rule out", "descartar"],
      ["run out of", "quedarse sin"],
      ["set aside", "reservar / dejar de lado"],
      ["set back", "retrasar"],
      ["set out", "emprender / proponer (argumento)"],
      ["stand for", "representar / tolerar"],
      ["stand out", "destacar"],
      ["take on", "asumir (responsabilidad)"],
      ["take over", "hacerse cargo de"],
      ["turn out", "resultar (ser)"],
      ["wear off", "desaparecer gradualmente (un efecto)"],
      ["work out", "funcionar / resolver / hacer ejercicio"],
      ["lead to", "llevar a, conducir a, dar como resultado"],
    ],
  },

  /* ================================================================
     SECCIÓN 6 — PHRASAL VERBS C1/C2 — COMUNICACIÓN Y PENSAMIENTO
     ================================================================ */
  {
    id: "phrasal-comunicacion",
    title: "Phrasal verbs: comunicación y pensamiento",
    note: "Especialmente útiles en producción escrita y en key word transformations.",
    kind: "pairs",
    items: [
      ["account for", "explicar, dar razón de / representar un %"],
      ["back up", "respaldar, apoyar (argumento)"],
      ["bear out", "confirmar, corroborar"],
      ["build on", "desarrollar, ampliar a partir de"],
      ["cast doubt on", "poner en duda"],
      ["draw on", "basarse en, nutrirse de"],
      ["dwell on", "insistir en, dar vueltas a"],
      ["enlarge on", "ampliar, desarrollar (un punto)"],
      ["expand on", "desarrollar, dar más detalle sobre"],
      ["follow through", "dar seguimiento, no abandonar"],
      ["gloss over", "pasar por alto, minimizar"],
      ["hammer out", "llegar a (un acuerdo) tras mucho esfuerzo"],
      ["hark back to", "remontarse a, evocar"],
      ["hinge on", "depender de, girar en torno a"],
      ["lay out", "exponer, presentar (un plan)"],
      ["leave out", "omitir, excluir"],
      ["lend itself to", "prestarse a (un tratamiento)"],
      ["pass off as", "hacer pasar por, hacerse pasar por"],
      ["point out", "señalar, indicar"],
      ["put down to", "atribuir a"],
      ["put up with", "aguantar, soportar"],
      ["refer back to", "remitir a, volver a mencionar"],
      ["run through", "repasar, recorrer rápidamente"],
      ["see through", "calar (a alguien) / acabar algo"],
      ["single out", "distinguir, señalar individualmente"],
      ["spell out", "explicar con detalle, deletrear"],
      ["stem from", "derivarse de, tener origen en"],
      ["sum up", "resumir"],
      ["talk round", "convencer a alguien"],
      ["throw light on", "arrojar luz sobre"],
      ["touch on", "tratar brevemente"],
      ["write off", "dar por perdido / amortizar"],
    ],
  },

  /* ================================================================
     SECCIÓN 7 — IDIOMS Y EXPRESIONES FIJAS (C1/C2)
     ================================================================ */
  {
    id: "idioms-c1c2",
    title: "Idioms y expresiones fijas C1/C2",
    note: "Imprescindibles para Gapped Sentences y MCQ. Memoriza el idiom completo como unidad.",
    kind: "pairs",
    items: [
      ["take sth in one's stride", "encajar algo sin inmutarse"],
      ["fly in the face of", "contradecir frontalmente"],
      ["on the grounds that", "alegando que, con el argumento de que"],
      ["for all intents and purposes", "a todos los efectos"],
      ["at odds with", "en contradicción con, en desacuerdo con"],
      ["in the wake of", "como consecuencia de, a raíz de"],
      ["on the verge of", "al borde de, a punto de"],
      ["to cast doubt on", "poner en duda"],
      ["to bear fruit", "dar frutos, surtir efecto"],
      ["to take a toll on", "pasar factura a, afectar negativamente"],
      ["to fall short of", "no llegar a, quedarse corto"],
      ["to come to terms with", "aceptar, asumir"],
      ["to draw a line under", "pasar página, dar por cerrado"],
      ["to turn a blind eye to", "hacer la vista gorda con"],
      ["to give the benefit of the doubt", "dar el beneficio de la duda"],
      ["once and for all", "de una vez por todas"],
      ["out of the blue", "de repente, sin previo aviso"],
      ["above board", "legítimo, transparente"],
      ["to sit on the fence", "no mojarse, mantenerse neutral"],
      ["to bite the bullet", "armarse de valor, aguantar"],
      ["to cut corners", "hacer las cosas de forma chapucera"],
      ["to get the upper hand", "llevar la delantera, imponerse"],
      ["to go hand in hand with", "ir de la mano de"],
      ["to have the upper hand", "tener ventaja, llevar la delantera"],
      ["to keep a low profile", "mantenerse en un segundo plano"],
      ["to leave no stone unturned", "no dejar piedra sin mover"],
      ["to lose sight of", "perder de vista"],
      ["to make headway", "avanzar, progresar"],
      ["to paint a grim picture", "pintar un panorama sombrío"],
      ["to play devil's advocate", "hacer de abogado del diablo"],
      ["to put sth into perspective", "poner algo en perspectiva"],
      ["to shed light on", "arrojar luz sobre"],
      ["to speak volumes", "decir mucho, ser muy revelador"],
      ["to stand the test of time", "resistir la prueba del tiempo"],
      ["to strike a balance", "encontrar un equilibrio"],
      ["to take precedence over", "tener prioridad sobre"],
      ["to tip the balance", "inclinar la balanza"],
      ["to weather the storm", "capear el temporal"],
      ["a double-edged sword", "un arma de doble filo"],
      ["a far cry from", "muy lejos de, muy distinto a"],
      ["a mixed blessing", "una bendición con trampa"],
      ["at the expense of", "a costa de"],
      ["by the same token", "del mismo modo, igualmente"],
      ["in the long run", "a largo plazo"],
      ["in no uncertain terms", "sin ambages, claramente"],
      ["on a par with", "al mismo nivel que"],
      ["to have a vested interest in", "tener un interés personal en"],
      ["to pave the way for", "allanar el camino para"],
      ["to break new ground", "abrir nuevos caminos, ser pionero"],
      ["see fit to", "juzgar oportuno, tener a bien — formal, a menudo con matiz crítico"],
    ],
  },

  /* ================================================================
     SECCIÓN 8 — PREPOSICIONES DEPENDIENTES
     ================================================================ */
  {
    id: "prepositions",
    title: "Preposiciones dependientes",
    note: "El error nº 1 en producción escrita. Memorízalas como bloque.",
    kind: "pairs",
    items: [
      ["depend", "on"], ["consist", "of"],
      ["result", "in (causar) / from (ser consecuencia de)"], ["rely", "on"],
      ["succeed", "in"], ["interested", "in"],
      ["capable", "of"], ["responsible", "for"],
      ["aware", "of"], ["accustomed", "to"],
      ["insist", "on"], ["approve", "of"],
      ["concerned", "about"], ["contribute", "to"],
      ["based", "on"], ["subject", "to"],
      ["in contrast", "to / with"], ["at the expense", "of"],
      ["attest", "to"], ["attribute", "to"],
      ["abstain", "from"], ["accuse", "of"],
      ["adapt", "to"], ["adhere", "to"],
      ["afflicted", "with/by"], ["agree", "with/on/to"],
      ["aim", "at"], ["amount", "to"],
      ["appeal", "to/against"], ["apply", "to/for"],
      ["aspire", "to"], ["associated", "with"],
      ["benefit", "from"], ["blame sb", "for"],
      ["boast", "of/about"], ["characteristic", "of"],
      ["collide", "with"], ["comply", "with"],
      ["conducive", "to"], ["conform", "to"],
      ["dedicated", "to"], ["deter sb", "from"],
      ["devote", "to"], ["differ", "from/with"],
      ["eligible", "for"], ["entitle", "to"],
      ["equivalent", "to"], ["exempt", "from"],
      ["familiar", "with"], ["fed up", "with"],
      ["fondness", "for"], ["grasp", "of"],
      ["hindered", "by"], ["impact", "on"],
      ["indulge", "in"], ["persist", "in"],
      ["preoccupied", "with"], ["pride oneself", "on"],
      ["prone", "to"], ["refrain", "from"],
      ["reluctant", "to"], ["stem", "from"],
      ["sympathize", "with"], ["tinker", "with"],
    ],
  },

  /* ================================================================
     SECCIÓN 9 — ORTOGRAFÍA
     ================================================================ */
  {
    id: "ortografia",
    title: "Ortografía británica y americana",
    note: "Ambas valen en Read and Select y en escritura. En Read and Complete, solo la americana.",
    kind: "pairs",
    items: [
      ["travelling, cancelled, modelling", "traveling, canceled, modeling"],
      ["centre, theatre, metre", "center, theater, meter"],
      ["colour, behaviour, favour", "color, behavior, favor"],
      ["organise, analyse, realise", "organize, analyze, realize"],
      ["defence, licence (n.)", "defense, license"],
      ["catalogue, dialogue", "catalog, dialog"],
      ["programme", "program"],
      ["grey", "gray"],
      ["judgement", "judgment"],
    ],
  },

  /* ================================================================
     SECCIÓN 10 — PALABRAS QUE CASI TODOS ESCRIBEN MAL
     ================================================================ */
  {
    id: "faltas",
    title: "Palabras que casi todos escriben mal",
    kind: "list",
    items: [
      "accommodate", "occurrence", "occurred", "necessary", "embarrass", "definitely",
      "separate", "privilege", "rhythm", "conscience", "conscientious", "maintenance",
      "recommend", "argument", "existence", "independent", "liaison", "millennium",
      "questionnaire", "restaurant", "threshold", "weird", "bureaucracy", "entrepreneur",
      "acquaintance", "indispensable", "perseverance", "supersede", "harass", "publicly",
      "foreign", "colleague", "exaggerate", "hierarchy", "noticeable", "parallel",
      "pronunciation", "referred", "relevant", "twelfth", "vacuum", "apparent",
      "committee", "curiosity", "guarantee", "immediately", "acknowledge", "aggressive",
      "apparently", "assassinate", "collaborate", "commitment", "consciously",
      "continuously", "desiccate", "dilemma", "diphthong", "disappear", "dumbbell",
      "ecstasy", "eighth", "fluorescent", "forty", "fuelling", "gauge", "grammar",
      "grievous", "handkerchief", "humorous", "hygiene", "hypocrisy", "ignorance",
      "inadvertent", "incidentally", "inoculate", "insistent", "intellectual",
      "irresistible", "legitimate", "leisure", "liquefy", "manoeuvre", "miniature",
      "mischievous", "misspell", "mysterious", "naïve", "necessary", "negligible",
      "occasionally", "occurred", "oscillate", "parliament", "perceive", "permanent",
      "perseverance", "phenomenal", "possess", "preceding", "prejudice", "prejudice",
      "prevalent", "psychology", "pursue", "receipt", "receive", "referred",
      "reminisce", "resistance", "rhyme", "ridiculous", "science", "seize",
      "siege", "sincerely", "skilful", "subtle", "succeed", "supersede",
      "surprise", "tomorrow", "unnecessary", "until", "withhold",
    ],
  },

  /* ================================================================
     SECCIÓN 11 — AFIJOS Y RAÍCES
     ================================================================ */
  {
    id: "afijos",
    title: "Afijos y raíces",
    note: "Identifica primero la categoría gramatical que pide el hueco, y luego el tiempo verbal.",
    kind: "groups",
    groups: [
      { label: "→ sustantivo", items: ["-tion / -sion (implication, provision)", "-ment (assessment)", "-ness (awareness)", "-ity (feasibility)", "-ance / -ence (reluctance, coherence)", "-ship (relationship)", "-hood (likelihood)", "-ism (activism)", "-ure (exposure)", "-cy (advocacy, complacency)", "-ry (rivalry, machinery)", "-th (strength, growth)", "-age (shortage, heritage)"] },
      { label: "→ adjetivo", items: ["-ous (ambiguous)", "-ive (disruptive)", "-al (marginal)", "-able / -ible (feasible, permissible)", "-ful / -less (resourceful, relentless)", "-ic (systematic)", "-ary (arbitrary)", "-ent / -ant (persistent, significant)", "-ate (passionate)", "-ory (contributory)", "-ward (outward)", "-some (troublesome, cumbersome)"] },
      { label: "→ verbo", items: ["-ize / -ise (prioritize)", "-ify (clarify)", "-ate (facilitate)", "-en (strengthen, widen)", "-esce (coalesce)"] },
      { label: "→ adverbio", items: ["-ly (conclusively, strategically)", "Cuidado: friendly, cowardly, elderly son adjetivos"] },
      { label: "prefijos frecuentes", items: ["un- / in- / im- / ir- / il- (negación)", "dis-", "mis- (mal)", "over- / under- (exceso o defecto)", "re- (de nuevo)", "pre- / post-", "sub- (inferior, debajo)", "inter- (entre)", "trans- (a través)", "anti-", "co-", "counter- (contra)", "pseudo-", "hyper- (exceso)", "macro- / micro-", "extra-", "semi-", "bi- / multi-", "self- (self-sufficient, self-evident)"] },
    ],
  },

  /* ================================================================
     SECCIÓN 12 — COLOCACIONES POR TEMA
     ================================================================ */
  {
    id: "colocaciones",
    title: "Colocaciones por tema",
    note: "Esto es lo que sube de C1 a C2 en producción.",
    kind: "groups",
    groups: [
      { label: "Tecnología e IA", items: ["a double-edged sword", "to reshape the landscape of", "algorithmic bias", "to blur the line between", "digital literacy", "a breeding ground for misinformation", "to streamline processes", "at the expense of privacy", "unprecedented access to", "to lag behind technologically", "echo chamber", "screen fatigue", "disruptive technology", "to harness the power of", "data-driven decisions", "artificial intelligence ethics"] },
      { label: "Educación y aprendizaje", items: ["rote memorization", "to foster critical thinking", "a one-size-fits-all approach", "to tailor instruction to", "lifelong learning", "academic rigour", "to bridge the achievement gap", "hands-on experience", "to instil a love of learning", "a stepping stone to", "to fall through the cracks", "to nurture talent", "peer-to-peer learning", "collaborative environment", "educational attainment"] },
      { label: "Medio ambiente", items: ["to curb emissions", "carbon footprint", "at an alarming rate", "to deplete natural resources", "a pressing concern", "environmentally conscious", "to mitigate the impact of", "renewable alternatives", "irreversible damage", "to strike a balance between growth and conservation", "biodiversity loss", "to phase out fossil fuels", "a vicious cycle", "net-zero target", "ecosystem resilience"] },
      { label: "Sociedad y justicia social", items: ["systemic inequality", "to marginalise communities", "a collective responsibility", "to raise awareness of", "civic engagement", "social mobility", "to bear the brunt of", "a safety net", "vested interests", "to level the playing field", "institutional racism", "gender pay gap", "intergenerational poverty", "to empower individuals", "grassroots movement"] },
      { label: "Trabajo y desarrollo profesional", items: ["to hone one's skills", "job satisfaction", "a demanding workload", "to climb the career ladder", "transferable skills", "burnout", "to negotiate terms", "a rewarding career path", "to take on responsibility", "work–life balance", "remote working arrangements", "to headhunt candidates", "corporate governance", "performance-related pay", "succession planning"] },
      { label: "Economía y finanzas", items: ["fiscal austerity", "to stimulate growth", "trade deficit", "inflationary pressure", "to weather a recession", "purchasing power", "labour market", "to undermine confidence", "profit margin", "supply chain disruption", "interest rate hike", "gross domestic product", "to tighten the belt", "hedge fund", "quantitative easing"] },
      { label: "Política y gobierno", items: ["bipartisan support", "to hold sb accountable", "electoral reform", "to wield influence", "checks and balances", "to push through legislation", "to yield concessions", "political landscape", "to bridge the divide", "the ruling coalition", "to overhaul the system", "geopolitical tensions", "to broker a deal", "foreign policy", "to ratify a treaty"] },
      { label: "Cultura y viajes", items: ["to broaden one's horizons", "deeply rooted traditions", "a melting pot of cultures", "culture shock", "off the beaten track", "to immerse oneself in", "a lasting impression", "cultural exchange", "to gain a fresh perspective", "architectural heritage", "a cosmopolitan city", "indigenous customs", "to preserve cultural identity"] },
      { label: "Salud y estilo de vida", items: ["a sedentary lifestyle", "to take a toll on", "to prioritise well-being", "mindful habits", "to build resilience", "chronic stress", "in moderation", "to unwind after a long day", "preventive healthcare", "mental health awareness", "holistic approach", "to lead an active lifestyle", "dietary habits", "obesity epidemic"] },
      { label: "Relaciones y comunidad", items: ["a sense of belonging", "to forge lasting friendships", "mutual respect", "to lend a hand", "common ground", "to keep in touch", "a tight-knit community", "to fall out with someone", "estranged relatives", "to bridge differences", "to mend fences", "social isolation", "intergenerational dialogue"] },
      { label: "Creatividad y arte", items: ["a form of self-expression", "to spark the imagination", "artistic licence", "to convey emotion", "a creative outlet", "to push boundaries", "a source of inspiration", "to resonate with an audience", "avant-garde movement", "commercial viability", "to capture the essence of", "evocative imagery", "critical acclaim"] },
      { label: "Ética y moral", items: ["a moral dilemma", "to weigh the pros and cons", "at odds with one's principles", "to draw the line at", "a grey area", "to act in good faith", "to hold oneself accountable", "conflicting interests", "ethical implications", "professional integrity", "transparent governance", "to set a precedent"] },
      { label: "Formas de «volver» — matices C2", items: [
        "return = volver/devolver (neutro, el más general): He returned to Madrid in June.",
        "retrace = desandar o reconstruir paso a paso: She retraced her steps to find the key.",
        "regress = retroceder a un estado anterior peor (connotación negativa): Without practice, your speaking will regress.",
        "resume ⚠️ = reanudar algo interrumpido (≠ resumir, ≠ résumé): Talks resumed after a two-week break.",
      ]},
      { label: "Describir fotos", items: ["in the foreground / in the background", "to the left / right of", "scattered across", "strewn with", "nestled between", "surrounded by", "appears to be", "what strikes me most is", "judging by their expressions", "a bustling scene", "dimly lit", "sun-drenched", "snow-capped peaks", "a steep climb", "engrossed in", "a contemplative mood", "hustle and bustle"] },
    ],
  },

  /* ================================================================
     SECCIÓN 13 — COLOCACIONES VERBO + SUSTANTIVO
     ================================================================ */
  {
    id: "verb-noun-col",
    title: "Colocaciones verbo + sustantivo",
    note: "Las colocaciones son la diferencia entre un C1 y un C2 en writing. Apréndalas de memoria.",
    kind: "pairs",
    items: [
      ["make a concession", "hacer una concesión"],
      ["reach a consensus", "llegar a un consenso"],
      ["raise objections", "plantear objeciones"],
      ["pose a challenge", "suponer un reto"],
      ["draw a conclusion", "extraer una conclusión"],
      ["strike a deal", "cerrar un trato"],
      ["bear consequences", "asumir las consecuencias"],
      ["cast doubt on", "poner en duda"],
      ["lay the groundwork for", "sentar las bases de"],
      ["run the risk of", "correr el riesgo de"],
      ["shoulder the blame", "asumir la culpa"],
      ["give credence to", "dar credibilidad a"],
      ["attach importance to", "dar importancia a"],
      ["take heed of", "hacer caso de, prestar atención a"],
      ["pay heed to", "prestar atención a"],
      ["hold sb accountable", "hacer a alguien responsable"],
      ["drive home a point", "recalcar un punto, hacerlo entender"],
      ["harbour doubts", "albergar dudas"],
      ["command respect", "imponer / ganarse el respeto"],
      ["seize the opportunity", "aprovechar la oportunidad"],
      ["spark a debate", "desencadenar un debate"],
      ["fuel speculation", "alimentar la especulación"],
      ["mount a challenge", "presentar un desafío"],
      ["forge an alliance", "forjar una alianza"],
      ["dispel a myth", "desmentir un mito"],
      ["fuel controversy", "avivar la polémica"],
      ["make inroads into", "abrirse camino en"],
      ["shed light on", "arrojar luz sobre"],
      ["stoke fears", "avivar los temores"],
      ["wield power", "ejercer el poder"],
    ],
  },

  /* ================================================================
     SECCIÓN 14 — COLOCACIONES ADJETIVO + SUSTANTIVO
     ================================================================ */
  {
    id: "adj-noun-col",
    title: "Colocaciones adjetivo + sustantivo",
    note: "Las colocaciones incorrectas son el error más frecuente en el Writing del C2.",
    kind: "pairs",
    items: [
      ["stark contrast", "contraste llamativo / acusado"],
      ["sweeping generalization", "generalización excesiva"],
      ["mounting pressure", "presión creciente"],
      ["wholesale change", "cambio radical, global"],
      ["deep-seated prejudice", "prejuicio arraigado"],
      ["far-reaching consequences", "consecuencias de gran alcance"],
      ["widespread concern", "preocupación generalizada"],
      ["pressing need", "necesidad urgente"],
      ["vested interest", "interés particular, interés creado"],
      ["fleeting impression", "impresión fugaz"],
      ["irrefutable evidence", "pruebas irrefutables"],
      ["imminent threat", "amenaza inminente"],
      ["overriding concern", "preocupación primordial"],
      ["innate ability", "capacidad innata"],
      ["inherent weakness", "debilidad intrínseca"],
      ["undue influence", "influencia indebida"],
      ["pivotal role", "papel fundamental / decisivo"],
      ["marginal improvement", "mejora marginal"],
      ["fundamental flaw", "defecto fundamental"],
      ["acute shortage", "escasez aguda"],
      ["complacent attitude", "actitud complaciente"],
      ["daunting prospect", "perspectiva intimidante"],
      ["prolific output", "producción prolífica"],
      ["grievous error", "error grave"],
      ["pervasive influence", "influencia generalizada"],
      ["marked improvement", "mejora notable"],
      ["glaring inconsistency", "incoherencia flagrante"],
      ["meticulous attention", "atención meticulosa"],
      ["unprecedented scale", "escala sin precedentes"],
      ["comprehensive review", "revisión exhaustiva"],
    ],
  },

  /* ================================================================
     SECCIÓN 15 — CONECTORES Y FRASES FUNCIONALES
     ================================================================ */
  {
    id: "conectores",
    title: "Conectores y frases funcionales",
    kind: "groups",
    groups: [
      { label: "Introducir", items: ["It is often argued that…", "There is little doubt that…", "At first glance, X may seem…, but…", "It is a widely held belief that…", "One of the most contentious issues today is…", "Central to this debate is the question of…"] },
      { label: "Añadir", items: ["Moreover", "Furthermore", "What is more", "Not only… but also…", "In addition to this", "Beyond that", "Over and above this", "Equally significant is…"] },
      { label: "Contrastar", items: ["However", "Nevertheless", "Conversely", "That said", "Whereas", "While it is true that…, it is equally important to…", "By contrast", "On the other hand", "Far from", "Notwithstanding"] },
      { label: "Conceder y rebatir", items: ["Admittedly, … yet…", "Granted, …", "Critics may contend that…, but this overlooks…", "One cannot deny that…, however,", "While there is some merit in this view,", "This argument holds water up to a point, but…"] },
      { label: "Ejemplificar", items: ["For instance", "A case in point is", "To illustrate", "Take, for example", "As evidenced by", "This is borne out by"] },
      { label: "Causa y consecuencia", items: ["Consequently", "As a result", "This gives rise to", "Owing to", "Hence", "Therefore", "By virtue of", "In the wake of", "On account of", "This paves the way for"] },
      { label: "Matizar la opinión", items: ["I would argue that", "It seems to me that", "To my mind", "I am inclined to think that", "There is a strong case for", "It could be argued that", "One might suggest that", "It stands to reason that"] },
      { label: "Restricción / condición", items: ["Provided (that)", "On the condition that", "As long as", "Only if", "Assuming that", "In the event that", "Failing that"] },
      { label: "Concluir", items: ["All things considered", "On balance", "Ultimately", "Taking everything into account", "In light of the above", "To sum up", "The evidence points to", "It can safely be concluded that"] },
    ],
  },

  /* ================================================================
     SECCIÓN 16 — ESTRUCTURAS GRAMATICALES QUE SUBEN LA NOTA
     ================================================================ */
  {
    id: "estructuras",
    title: "Estructuras que suben la nota",
    kind: "groups",
    groups: [
      { label: "Relativas", items: ["…, which suggests that…", "…, whose impact is felt…", "…, at which point…", "…, from which it follows that…"] },
      { label: "Inversión", items: ["Not only does this…, but it also…", "Rarely have I encountered…", "Only when… did I realise…", "Under no circumstances should…", "Hardly had… when…", "No sooner had… than…", "Little did they know that…", "At no point did the committee…"] },
      { label: "Condicionales avanzados", items: ["Had I known…, I would have…", "Were it not for…", "Should this prove impossible,…", "Were this to be the case,…", "Had the situation deteriorated,…"] },
      { label: "Enfáticas (cleft)", items: ["What matters most is…", "It is precisely this that…", "What struck me was…", "It was not until… that…", "The reason why… is that…"] },
      { label: "Participiales", items: ["Having considered both sides, …", "Faced with such a choice, …", "Driven by the need to…", "Given the evidence above,…", "Seen from this perspective,…"] },
      { label: "Modales de matiz", items: ["may well", "might arguably", "could conceivably", "would tend to", "is bound to", "is likely to", "would appear to"] },
      { label: "Nominalizaciones", items: ["the introduction of → introducing", "a reduction in → reducing", "an increase in → increasing", "the failure to → failing to"] },
    ],
  },

  /* ================================================================
     SECCIÓN 17 — VOCABULARIO DE CRIME & LAW
     ================================================================ */
  {
    id: "crime-law",
    title: "Crimen y sistema legal",
    note: "Temas recurrentes en Reading y Use of English de CPE/CAE.",
    kind: "pairs",
    items: [
      ["accomplice", "cómplice"],
      ["acquit", "absolver"],
      ["allegation", "acusación, alegación"],
      ["arson", "incendio provocado"],
      ["bail", "fianza"],
      ["bribery", "soborno"],
      ["burglary", "robo en domicilio"],
      ["clemency", "clemencia, misericordia judicial"],
      ["collusion", "colusión, connivencia"],
      ["conviction", "condena, convicción"],
      ["culpable", "culpable"],
      ["deterrent", "elemento disuasorio"],
      ["embezzlement", "malversación de fondos"],
      ["extortion", "extorsión"],
      ["fraud", "fraude"],
      ["grievance", "queja, agravio"],
      ["indict", "encausar, procesar"],
      ["incarceration", "encarcelamiento"],
      ["jurisdiction", "jurisdicción"],
      ["larceny", "hurto"],
      ["laundering (money)", "blanqueo de dinero"],
      ["liability", "responsabilidad legal"],
      ["manslaughter", "homicidio sin premeditación"],
      ["misconduct", "conducta impropia"],
      ["perpetrator", "autor, perpetrador"],
      ["prosecution", "acusación, enjuiciamiento"],
      ["sentence", "condena (noun) / sentenciar (verb)"],
      ["smuggling", "contrabando"],
      ["testimony", "testimonio"],
      ["vandalism", "vandalismo"],
      ["verdict", "veredicto"],
      ["witness", "testigo"],
    ],
  },

  /* ================================================================
     SECCIÓN 18 — VOCABULARIO CIENTÍFICO Y TECNOLÓGICO
     ================================================================ */
  {
    id: "science-tech",
    title: "Ciencia y tecnología",
    note: "Muy presente en Reading Parts 5, 6 y 7 del CPE.",
    kind: "pairs",
    items: [
      ["algorithm", "algoritmo"],
      ["autonomous", "autónomo"],
      ["binary", "binario"],
      ["breakthrough", "avance decisivo"],
      ["calibrate", "calibrar"],
      ["catalyst", "catalizador"],
      ["chronic", "crónico"],
      ["cognition", "cognición, funcionamiento mental"],
      ["compound", "compuesto (adj/sust)"],
      ["corroborate", "corroborar"],
      ["empirical", "empírico"],
      ["encryption", "cifrado, encriptación"],
      ["genome", "genoma"],
      ["hypothesis", "hipótesis"],
      ["infrastructure", "infraestructura"],
      ["innate", "innato"],
      ["iterate", "iterar, repetir el proceso"],
      ["longitudinal", "longitudinal (estudio)"],
      ["nanotechnology", "nanotecnología"],
      ["neural", "neural"],
      ["paradigm", "paradigma"],
      ["particle", "partícula"],
      ["peer review", "revisión por pares"],
      ["prototype", "prototipo"],
      ["quantum", "cuántico"],
      ["replication", "replicación (de experimento)"],
      ["semiconductor", "semiconductor"],
      ["simulation", "simulación"],
      ["synthesis", "síntesis"],
      ["variable", "variable"],
    ],
  },

  /* ================================================================
     SECCIÓN 19 — VOCABULARIO LITERARIO Y ARTÍSTICO
     ================================================================ */
  {
    id: "literary-art",
    title: "Literatura y arte",
    note: "Clave para el Paper 2 (Writing) y para Reading literario.",
    kind: "pairs",
    items: [
      ["allegory", "alegoría"],
      ["ambivalent", "ambivalente"],
      ["anachronistic", "anacrónico"],
      ["cathartic", "catártico"],
      ["cynical", "cínico"],
      ["depict", "representar, describir"],
      ["dystopian", "distópico"],
      ["enigmatic", "enigmático"],
      ["evocative", "evocador"],
      ["genre", "género literario/artístico"],
      ["grotesque", "grotesco"],
      ["harrowing", "desgarrador"],
      ["idyllic", "idílico"],
      ["ironic", "irónico"],
      ["juxtapose", "yuxtaponer"],
      ["melancholic", "melancólico"],
      ["metaphorical", "metafórico"],
      ["motif", "motivo (tema recurrente)"],
      ["narrative", "narrativa"],
      ["nuanced", "matizado, con matices"],
      ["paradoxical", "paradójico"],
      ["pastoral", "pastoril, bucólico"],
      ["poignant", "emotivo, conmovedor"],
      ["satirical", "satírico"],
      ["seminal", "seminal, fundacional"],
      ["subversive", "subversivo"],
      ["surreal", "surrealista"],
      ["symbolism", "simbolismo"],
      ["thematic", "temático"],
      ["witty", "ingenioso, agudo"],
    ],
  },

  /* ================================================================
     SECCIÓN 20 — VERBOS FORMALES (WRITING C2)
     ================================================================ */
  {
    id: "formal-verbs",
    title: "Verbos formales para el writing",
    note: "Sustituye los verbos simples por estos en tu escritura de nivel C2.",
    kind: "pairs",
    items: [
      ["say → contend / assert / maintain", "sostener, afirmar, mantener"],
      ["show → demonstrate / illustrate / reveal", "demostrar, ilustrar, revelar"],
      ["think → argue / consider / suggest", "argumentar, considerar, sugerir"],
      ["help → facilitate / assist / foster", "facilitar, asistir, fomentar"],
      ["cause → trigger / prompt / generate", "desencadenar, motivar, generar"],
      ["make worse → exacerbate / aggravate / compound", "exacerbar, agravar, agudizar"],
      ["make better → alleviate / ameliorate / mitigate", "aliviar, mejorar, mitigar"],
      ["need → necessitate / require / demand", "necesitar, requerir, demandar"],
      ["keep → retain / preserve / sustain", "retener, preservar, sostener"],
      ["start → initiate / commence / embark on", "iniciar, comenzar, embarcarse en"],
      ["stop → cease / abandon / discontinue", "cesar, abandonar, interrumpir"],
      ["change → transform / alter / modify", "transformar, alterar, modificar"],
      ["use → employ / utilise / harness", "emplear, utilizar, aprovechar"],
      ["see → observe / perceive / witness", "observar, percibir, ser testigo de"],
      ["try → endeavour / attempt / strive", "intentar, esforzarse, procurar"],
      ["get → obtain / acquire / attain", "obtener, adquirir, alcanzar"],
      ["give → provide / offer / impart", "proporcionar, ofrecer, impartir"],
      ["look at → examine / scrutinise / assess", "examinar, escrutar, evaluar"],
      ["deal with → address / tackle / contend with", "abordar, hacer frente a, lidiar con"],
      ["plan → devise / formulate / draw up", "idear, formular, elaborar"],
    ],
  },

  /* ================================================================
     SECCIÓN 21 — FRASES TÍPICAS GAPPED SENTENCES
     ================================================================ */
  {
    id: "gapped-key",
    title: "Palabras polisémicas para Gapped Sentences",
    note: "Una sola palabra que encaja en frases muy distintas. Aprende los usos múltiples.",
    kind: "pairs",
    items: [
      ["run", "run for office / a show runs / run sth past sb / run the risk"],
      ["ground", "break new ground / stand your ground / cover a lot of ground / on the grounds that"],
      ["hold", "hold your ground / hold a meeting / hold your breath / hold sb accountable"],
      ["draw", "draw a conclusion / draw on resources / draw a crowd / draw the line"],
      ["bear", "bear in mind / bear fruit / bear the brunt / bear resemblance"],
      ["make", "make the most of / make light of / make sense / make inroads into"],
      ["take", "take a toll / take precedence / take the reins / take issue with"],
      ["fall", "fall short of / fall through / fall back on / fall out with"],
      ["pass", "pass the buck / pass judgment / pass muster / pass off as"],
      ["raise", "raise the bar / raise objections / raise awareness / raise the stakes"],
      ["set", "set aside / set the scene / set a precedent / set back"],
      ["turn", "turn a blind eye / turn the tide / turn out / turn down"],
      ["cut", "cut corners / cut ties with / cut to the chase / cut short"],
      ["break", "break new ground / break ranks / break even / break the mould"],
      ["give", "give the benefit of the doubt / give way to / give rise to / give credit"],
    ],
  },

  /* ================================================================
     SECCIÓN 22 — PALABRAS NEGATIVAS FRECUENTES
     ================================================================ */
  {
    id: "negative-vocab",
    title: "Vocabulario de negación y restricción",
    note: "Muy frecuentes en Open Cloze y en transformaciones con inversión.",
    kind: "pairs",
    items: [
      ["by no means", "en absoluto, de ninguna manera"],
      ["in no way", "de ninguna manera"],
      ["on no account", "bajo ningún concepto"],
      ["under no circumstances", "bajo ninguna circunstancia"],
      ["at no point", "en ningún momento"],
      ["not in the least", "en absoluto, para nada"],
      ["to no avail", "en vano, sin éxito"],
      ["without exception", "sin excepción"],
      ["far from", "lejos de, de ningún modo"],
      ["let alone", "ni siquiera, y mucho menos"],
      ["hardly / scarcely / barely + past perfect", "inversión: apenas había... cuando"],
      ["no sooner... than", "no bien... cuando"],
      ["neither... nor", "ni... ni"],
      ["nothing short of", "nada menos que, auténtico"],
      ["anything but", "todo menos, en absoluto"],
    ],
  },

  /* ================================================================
     SECCIÓN 23 — EXPRESIONES DE CANTIDAD Y GRADO
     ================================================================ */
  {
    id: "degree-quantity",
    title: "Expresiones de grado y cantidad",
    note: "Imprescindibles para Multiple-Choice Cloze y Open Cloze.",
    kind: "pairs",
    items: [
      ["a great deal of", "una gran cantidad de (incontables)"],
      ["a wide range of", "una amplia gama de"],
      ["a host of", "una gran cantidad de"],
      ["a handful of", "un puñado de, unos pocos"],
      ["a fraction of", "una fracción de, mucho menos que"],
      ["the vast majority of", "la gran mayoría de"],
      ["a growing number of", "un número creciente de"],
      ["an increasing proportion of", "una proporción cada vez mayor de"],
      ["to a great extent", "en gran medida"],
      ["to some extent", "hasta cierto punto"],
      ["to a limited extent", "en cierta medida limitada"],
      ["by far", "con mucho, de lejos"],
      ["considerably more / less", "considerablemente más / menos"],
      ["substantially fewer", "considerablemente menos"],
      ["marginally better", "ligeramente mejor"],
      ["exponentially", "exponencialmente"],
      ["disproportionately", "desproporcionadamente"],
      ["overwhelmingly", "abrumadoramente"],
      ["scarcely any", "apenas ninguno"],
      ["precious few", "muy pocos, poquísimos"],
    ],
  },

  /* ================================================================
     SECCIÓN 24 — VOCABULARIO SOCIEDAD Y MEDIOS
     ================================================================ */
  {
    id: "society-media",
    title: "Sociedad, medios y política",
    note: "Presentes en casi todos los textos de Reading y Writing del CPE.",
    kind: "pairs",
    items: [
      ["accountability", "rendición de cuentas"],
      ["advocacy", "defensa (de una causa)"],
      ["backlash", "reacción violenta / rechazo masivo"],
      ["censorship", "censura"],
      ["civic", "cívico"],
      ["cohesion", "cohesión"],
      ["complacency", "autocomplacencia"],
      ["consensus", "consenso"],
      ["constituency", "circunscripción / grupo de apoyo"],
      ["corruption", "corrupción"],
      ["cronyism", "amiguismo"],
      ["demographics", "demografía"],
      ["disparity", "disparidad, desigualdad"],
      ["disenfranchised", "privado de derechos"],
      ["dissent", "disidencia, discrepancia"],
      ["electorate", "electorado"],
      ["faction", "facción"],
      ["grassroots", "de base, popular"],
      ["incumbent", "titular (del cargo)"],
      ["lobbyist", "grupo de presión, lobista"],
      ["mandate", "mandato"],
      ["monopoly", "monopolio"],
      ["oligarchy", "oligarquía"],
      ["propaganda", "propaganda"],
      ["pundit", "experto mediático, comentarista"],
      ["referendum", "referéndum"],
      ["rhetoric", "retórica"],
      ["scrutiny", "escrutinio"],
      ["sovereignty", "soberanía"],
      ["transparency", "transparencia"],
    ],
  },
  {
    id: "lexico-adicional",
    title: "Léxico adicional y agrícola",
    note: "Vocabulario, verbos y adjetivos nuevos de la lección.",
    kind: "pairs",
    items: [
      ["crop", "cultivo, cosecha (planta)"],
      ["harvest", "recolección, cosecha recogida"],
      ["soil", "tierra, suelo agrícola"],
      ["mulching", "acolchado (de tierra)"],
      ["cull", "sacrificar selectivamente / descartar / entresacar"],
      ["circumscribed", "limitado, restringido, acotado"],
      ["unyielding", "inflexible, que no cede"],
      ["fundamental", "fundamental, esencial (fundamental to)"],
      ["unforeseen", "imprevisto, inesperado"],
      ["high in fat", "alto en grasas (high in...)"],
      ["eagerly awaited", "esperado con ansia, muy esperado"],
      ["loom", "cernerse, asomar de forma amenazante"],
      ["postpone", "aplazar, posponer"],
      ["speed up", "acelerar (informal)"],
      ["streamline", "simplificar y agilizar (proceso)"],
      ["make loan approvals", "tramitar/conceder aprobaciones de préstamos"],
      ["peruse", "leer con detenimiento, examinar a fondo"],
      ["come in", "entrar / llegar (datos, resultados) / intervenir"],
      ["warrant", "justificar, merecer (v.) / orden judicial (n.)"],
      ["run low", "quedarse sin, ir quedándose bajo de (run low on)"],
      ["feel spent", "sentirse agotado, exhausto"],
      ["spare", "ahorrar (algo desagradable a alguien) / spare me: ahórramelo"],
      ["glad", "contento, alegre (solo predicativo)"],
      ["in the near term", "a corto plazo"],
      ["due", "con fecha prevista, pendiente de entrega / debido a"],
      ["dude", "tío, colega (slang informal)"],
    ],
  },
];
